name: 'LLVM installation commands'

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        sudo apt-get update
      shell: bash

    - name: Install clang and flang
      run: |
        sudo apt-get install -y clang flang
      shell: bash

    - name: Install MPI and OpenMP
      run: |
        sudo apt-get install -y libopenmpi-dev openmpi-bin
        sudo apt-get install -y libomp-dev libomp5
      shell: bash

    - name: Install LaPack
      run:
        sudo apt-get install libblas-dev liblapack-dev
      shell: bash

    - name: Install Valgrind
      run:
        sudo apt-get install valgrind
      shell: bash
