name: 'LLVM installation commands'

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        sudo apt-get update
      shell: bash

    - name: Install brew requirements
      run: |
        sudo apt-get install build-essential procps curl file git
      shell: bash

    # https://docs.brew.sh/Homebrew-on-Linux
    # https://greenwebpage.com/community/how-to-install-and-use-homebrew-on-ubuntu-24-04/
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo >> /home/runner/.bashrc
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
      shell: bash

    - name: Set up Homebrew
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew --version
      shell: bash

    - name: Add Homebrew to PATH
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH" >> $GITHUB_ENV
        brew --version
      shell: bash

    - name: Test Homebrew
      run: |
        brew --version
        brew install hello
      shell: bash

    - name: Install flang with Homebrew
      run: |
        brew install flang
      shell: bash
  
    - name: Add flang to LD_LIBRARY_PATH
      run: |
        echo "LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    
    - name: Install clang with apt-get
      run: |
        sudo apt-get install -y clang
      shell: bash


    - name: Create flang symlink
      run: |
        which flang-new
        flang-new --version
        sudo ln -sf /usr/bin/flang-new /usr/local/bin/flang
        which flang
        flang --version
      shell: bash

    - name: Install MPI and OpenMP
      run: |
        sudo apt-get install -y libopenmpi-dev openmpi-bin
        sudo apt-get install -y libomp-dev libomp5
      shell: bash

    - name: Install LaPack
      run:
        sudo apt-get install libblas-dev liblapack-dev
      shell: bash

    - name: Install Valgrind
      run:
        sudo apt-get install valgrind
      shell: bash
