name: 'LLVM installation commands'

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        sudo apt-get update
      shell: bash

    - name: Install brew requirements
      run: |
        sudo apt-get install build-essential procps curl file git
      shell: bash

    # https://docs.brew.sh/Homebrew-on-Linux
    # https://greenwebpage.com/community/how-to-install-and-use-homebrew-on-ubuntu-24-04/
    - name: Install brew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> $GITHUB_ENV
        eval "$($(brew --prefix)/bin/brew shellenv)"
      shell: bash

    - name: Test brew
      run: |
        brew --version
        brew install hello
      shell: bash

    - name: Install clang and flang
      run: |
        brew install clang
        brew install flang
      shell: bash
    
    - name: Create flang symlink
      run: |
        which flang-new
        flang-new --version
        sudo ln -sf /usr/bin/flang-new /usr/local/bin/flang
        which flang
        flang --version
      shell: bash

    - name: Install MPI and OpenMP
      run: |
        sudo apt-get install -y libopenmpi-dev openmpi-bin
        sudo apt-get install -y libomp-dev libomp5
      shell: bash

    - name: Install LaPack
      run:
        sudo apt-get install libblas-dev liblapack-dev
      shell: bash

    - name: Install Valgrind
      run:
        sudo apt-get install valgrind
      shell: bash
