name: 'LLVM installation commands'

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        sudo apt-get update
      shell: bash

    - name: Install clang and flang
      if: steps.cache-llvm-restore.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y clang flang
      shell: bash

    - name: Install MPI
      run: |
        sudo apt-get install -y libopenmpi-dev openmpi-bin
      shell: bash

    - name: Install LaPack
      run:
        sudo apt-get install libblas-dev liblapack-dev
      shell: bash

    - name: Install Valgrind
      run:
        sudo apt-get install valgrind
      shell: bash
