name: 'LLVM installation commands'

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        sudo apt-get update
      shell: bash

    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#homebrew-note
    - name: Install compilers with Homebrew
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew --version
        brew install llvm
        brew install flang
        brew install libomp
        brew install open-mpi
        clang --version
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      shell: bash
  
    - name: Ensure installed libraries can be discovered during compilation and runtime
      run: |
        ls /home/linuxbrew/.linuxbrew/
        echo "-------------------------"
        ls /home/linuxbrew/.linuxbrew/opt/
        echo "-------------------------"
        ls /home/linuxbrew/.linuxbrew/opt/open-mpi
        echo "-------------------------"
        ls /home/linuxbrew/.linuxbrew/opt/openmpi
        echo "-------------------------"
        echo "LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/libomp/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/libomp/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=/home/linuxbrew/.linuxbrew:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
        echo "OMPI_CC=clang" >> $GITHUB_ENV
        echo "OMPI_CXX=clang++" >> $GITHUB_ENV
        echo "OMPI_FC=flang" >> $GITHUB_ENV
      shell: bash

    - name: Create flang symlink
      run: |
        which flang-new
        flang-new --version
        ldd $(which flang-new)
        sudo ln -sf /usr/bin/flang-new /usr/local/bin/flang
        which flang
        flang --version
      shell: bash

    - name: Install LaPack
      run:
        sudo apt-get install libblas-dev liblapack-dev
      shell: bash

    - name: Install Valgrind
      run:
        sudo apt-get install valgrind
      shell: bash
