name: 'Pyccel pip commands for testing'

runs:
  using: "composite"
  steps:
    - name: Update pip
      shell: python
      run: |
        import pyccel
        from os.path import exists, join
        pyccel_loc = pyccel.__path__[0]
        print(pyccel_loc)
        assert(exists(join(pyccel_loc,'stdlib','internal','openmp.pyccel')))
