name: 'Pyccel pip commands for testing'

runs:
  using: "composite"
  steps:
    - name: Update pip
      shell: python
      run: |
        import pyccel, os
        from os.path import exists, join
        os.chdir('.')
        contents = os.listdir()
        for item in contents:
          print("===---------===> ", item)
        os.chdir('extensions/STC')
        contents = os.listdir()
        for item in contents:
          print("===---------===> ", item)
        pyccel_loc = pyccel.__path__[0]
        print(pyccel_loc)
        assert(exists(join(pyccel_loc,'stdlib','internal','openmp.pyccel')))
