name: 'Posting in progress status'
inputs:
  installation_token:
    description: "The GitHub API token of the bot"
    required: true
  run_id:
    description: "The id of the check run"
    required: true
  status:
    description: "The final status of the workflow"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Collecting status"
      run: |
        import os
        import json
        if os.path.exists('test_json_result.json'):
            with open('test_json_result.json', 'r') as f:
                result = json.load(f)
        else:
            result = {}
        result["details_url"] = "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        result["status"] = "${{ inputs.status }}"
        
        with open('test_json_result.json', 'w') as f:
            json.dump(result, f)
      shell: python
    - name: "Posting"
      run: |
        json_result=$(cat test_json_result.json)
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.installation_token }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          --url https://api.github.com/repos/${{ github.repository }}/check-runs/${{ inputs.run_id }} \
          -d "${json_result}"
      shell: shell
