paths:
  - pyccel
  - ci_tools
skip_magic: True
skip_init: True
fail_under: 0
ignore_patterns:
  pyccel/parser/syntactic.py:
    - "_visit_.*"
  pyccel/parser/semantic.py:
    - "_visit_.*"
  pyccel/codegen/printing/*code.py:
    - "_print_.*"
