skip_magic: True
skip_init: True
fail_under: 0
exclude:
  ".*/pyccel/extensions"
ignore_patterns:
  "syntactic":
    - "_visit_.*"
  "semantic":
    - "_visit_.*"
  ".*code":
    - "_print_.*"
  ".*_wrapper":
    - "_extract_.*_FunctionDefArgument"
    - "_extract_.*_FunctionDefResult"
