[default]
locale = 'en'
extend-ignore-re = ["Big Sur"]

[default.extend-words]
# Don't correct these word (parts)
ND = "ND"
arange = "arange"
iterm = "iterm"

[files]
extend-exclude = ["pyccel/extensions/*",
                  ]

