name: 'Pyccel pytest commands generating Cuda'
inputs:
  shell_cmd:
    description: 'Specifies the shell command (different for anaconda)'
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: Ccuda tests with pytest
      run: |
        # Catch exit 5 (no tests found)
        python -m pytest -rX ${FLAGS} -m "not (xdist_incompatible or parallel) and cuda ${{ inputs.pytest_mark }}" -sxv -k test_host_array --ignore=symbolic --ignore=ndarrays 2>&1 | tee s1_outfile.out
        pyccel-clean
      shell: ${{ inputs.shell_cmd }}
      working-directory: ./tests
    - name: Final step
      if: always()
      id: status
      run:
        python ci_tools/json_pytest_output.py -t "Cuda Test Summary" --tests "Cuda tests:${{ steps.pytest_1.outcome }}:tests/s1_outfile.out"
                      
      shell: ${{ inputs.shell_cmd }}
