name: 'Pyccel pytest commands generating Ccuda'
inputs:
  shell_cmd:
    description: 'Specifies the shell command (different for anaconda)'
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: Ccuda tests with pytest
      run: |
        python -m pytest -n auto -rx -m "not (parallel or xdist_incompatible) and ccuda" --ignore=symbolic --ignore=ndarrays --verbose -s
        pyccel-clean
      shell: ${{ inputs.shell_cmd }}
      working-directory: ./tests
