name: 'Intel installation commands'

runs:
  using: "composite"
  steps:
    - name: update the package list
      run:
        sudo apt-get update
      shell: bash
    - name: Restore cached Intel
      id: cache-intel-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          /opt/intel/oneapi/
        key: ${{ runner.os }}-intel-2024
        restore-keys: |
          ${{ runner.os }}-intel-
    - name: Install Intel OneAPI
      if: steps.cache-intel-restore.outputs.cache-hit != 'true'
      run: |
        # See https://www.intel.com/content/www/us/en/developer/tools/oneapi/hpc-toolkit-download.html?operatingsystem=linux&distributions=aptpackagemanager
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
          | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt update
        sudo apt install intel-hpckit
      shell: bash
    - name: Save Intel environment variables
      run: |
        source /opt/intel/oneapi/setvars.sh
        echo "$PATH" > $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$LIBRARY_PATH" >> $GITHUB_ENV
        echo "ONEAPI_ROOT=$ONEAPI_ROOT" >> $GITHUB_ENV
        echo "MANPATH=$MANPATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
        echo "TBB_ROOT=$TBB_ROOT" >> $GITHUB_ENV
        echo "ONEAPI_ROOT=$ONEAPI_ROOT" >> $GITHUB_ENV
        echo "ACL_BOARD_VENDOR_PATH=$ACL_BOARD_VENDOR_PATH" >> $GITHUB_ENV
        echo "FPGA_VARS_DIR=$FPGA_VARS_DIR" >> $GITHUB_ENV
        echo "I_MPI_ROOT=$I_MPI_ROOT" >> $GITHUB_ENV
        echo "FI_PROVIDER_PATH=$FI_PROVIDER_PATH" >> $GITHUB_ENV
        echo "DIAGUTIL_PATH=$DIAGUTIL_PATH" >> $GITHUB_ENV
        echo "GDB_INFO=$GDB_INFO" >> $GITHUB_ENV
        echo "CMPLR_ROOT=$CMPLR_ROOT" >> $GITHUB_ENV
        echo "INFOPATH=$INFOPATH" >> $GITHUB_ENV
        echo "OCL_ICD_FILENAMES=$OCL_ICD_FILENAMES" >> $GITHUB_ENV
        echo "CLASSPATH=$CLASSPATH" >> $GITHUB_ENV
        echo "INTELFPGAOCLSDKROOT=$INTELFPGAOCLSDKROOT" >> $GITHUB_ENV
        echo "MKLROOT=$MKLROOT" >> $GITHUB_ENV
        echo "NLSPATH=$NLSPATH" >> $GITHUB_ENV
        echo "INTEL_PYTHONHOME=$INTEL_PYTHONHOME" >> $GITHUB_ENV
        echo "CPATH=$CPATH" >> $GITHUB_ENV
        mpicc --version
      shell: bash
    - name: Save Intel Cache
      id: cache-intel-save
      uses: actions/cache/save@v3
      with:
        path: |
          /opt/intel/oneapi/
        key: ${{ steps.cache-intel-restore.outputs.cache-primary-key }}
    - name: Install Valgrind
      run:
        sudo apt-get install valgrind
      shell: bash
