name: 'Pyccel pip commands for testing'

runs:
  using: "composite"
  steps:
    - name: Update pip
      shell: bash
      run:
        python -m pip install --upgrade pip
    - name: Install wheel
      shell: bash
      run:
        python -m pip install wheel
    - name: Install pyccel
      shell: bash
      run:
        python -m pip install .
    - name: Install scipy
      shell: bash
      run:
        python -m pip install scipy
    - name: Install mpi4py
      shell: bash
      run:
        python -m pip install mpi4py
    - name: Install tblib
      shell: bash
      run:
        python -m pip install tblib
    - name: Install pytest
      shell: bash
      run:
        python -m pip install "pytest>=4.5"

