name: 'Pyccel pip commands for testing'

runs:
  using: "composite"
  steps:
    - name: Update pip
      shell: bash
      run:
        python -m pip install --upgrade pip
    - name: Install wheel
      shell: bash
      run:
        python -m pip install wheel
    - name: Install Pyccel and its Python dependencies
      shell: bash
      run:
        python -m pip install .[test]
