name: 'Pyccel pytest commands generating fortran or c'
inputs:
  shell_cmd:
    description: 'Specifies the shell command (different for anaconda)'
    required: false
    default: "bash"


runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        which python
        python -m pytest -n auto -rXx -v -m "not (parallel or xdist_incompatible) and c" --ignore=symbolic --ignore=ndarrays
        python -m pytest -rXx -m "xdist_incompatible and not parallel and c" --ignore=symbolic --ignore=ndarrays
        pyccel-clean
        touch ../pyccel/stdlib/ndarrays/ndarrays.h
        python -m pytest -n auto -rXx -m "not (parallel or xdist_incompatible) and not (c or python)" --ignore=symbolic --ignore=ndarrays
        python -m pytest -rXx -m "xdist_incompatible and not parallel and not (c or python)" --ignore=symbolic --ignore=ndarrays
        pyccel-clean
        python -m pytest ndarrays/ -rXx
        pyccel-clean
      shell: ${{ inputs.shell_cmd }}
      working-directory: ./tests
