name: 'Pyccel pytest commands generating fortran or c'
inputs:
  shell_cmd:
    description: 'Specifies the shell command (different for anaconda)'
    required: false
    default: 'bash'
  pytest_mark:
    description: 'Mark expression to exclude additional tests'
    required: false
    default: ''


runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        which python
        df -h
        python -m pytest -n auto -xv -rXx -v -m "not (parallel or xdist_incompatible) and c ${{ inputs.pytest_mark }}" --ignore=symbolic --ignore=ndarrays
        df -h
        if [ -n "${SITE_DIR}" ]; then
            echo "Touching"
            # Test ndarray folder update (requires parallel tests to avoid clean)
            touch ${SITE_DIR}/pyccel/stdlib/cwrapper/cwrapper.h
            python -m pytest -n auto -xv -rXx -v -m c -k test_array_int32_1d_scalar epyccel/test_arrays.py
        fi
        df -h
        python -m pytest -xv -rXx -m "xdist_incompatible and not parallel and c ${{ inputs.pytest_mark }}" --ignore=symbolic --ignore=ndarrays
        df -h
        ls
        ls __epyccel__
        ls __epyccel__/__pyccel__
        pyccel-clean
        df -h
        python -m pytest -n auto -xv -rXx -m "not (parallel or xdist_incompatible) and not (c or python) ${{ inputs.pytest_mark }}" --ignore=symbolic --ignore=ndarrays epyccel/recognised_functions
        df -h
        pyccel-clean
        df -h
        python -m pytest -n auto -xv -rXx -m "not (parallel or xdist_incompatible) and not (c or python) ${{ inputs.pytest_mark }}" --ignore=symbolic --ignore=ndarrays --ignore=epyccel/recognised_functions epyccel
        df -h
        pyccel-clean
        df -h
        python -m pytest -n auto -xv -rXx -m "not (parallel or xdist_incompatible) and not (c or python) ${{ inputs.pytest_mark }}" --ignore=symbolic --ignore=ndarrays --ignore=epyccel
        df -h
        pyccel-clean
        df -h
        python -m pytest -xv -rXx -m "xdist_incompatible and not parallel and not (c or python) ${{ inputs.pytest_mark }}" --ignore=symbolic --ignore=ndarrays
        df -h
        pyccel-clean
        df -h
        python -m pytest ndarrays/ -rXx
        df -h
        pyccel-clean
        df -h
      shell: ${{ inputs.shell_cmd }}
      working-directory: ./tests
