name: 'Pyccel pytest commands generating fortran or c'
inputs:
  anaconda:
    description: 'Specifies if anaconda is used'
    required: true


runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        which python
        python -m pytest -n auto -rX -m "not (parallel or xdist_incompatible) and c" --ignore=symbolic --ignore=ndarrays
        python -m pytest -rX -m "xdist_incompatible and not parallel and c" --ignore=symbolic --ignore=ndarrays
        pyccel-clean
        python -m pytest -n auto -rX -m "not (parallel or xdist_incompatible) and not (c or python)" --ignore=symbolic --ignore=ndarrays
        python -m pytest -rX -m "xdist_incompatible and not parallel and not (c or python)" --ignore=symbolic --ignore=ndarrays
        pyccel-clean
        python -m pytest ndarrays/ -rX
        pyccel-clean
      shell: ${{ inputs.anaconda }}
      working-directory: ./tests
