name: 'Pyccel pytest commands'

runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        cd tests
        python -m pytest -rx -m "not parallel and c" --ignore=ast --ignore=printers --ignore=symbolic --ignore=ndarrays
        python -m pytest -rx -m "not parallel and not c" --ignore=ast --ignore=printers --ignore=symbolic --ignore=ndarrays
        python -m pytest ndarrays/ -rx
        mpiexec -n 4 ${MPI_OPTS} python -m pytest epyccel/test_parallel_epyccel.py -v -m parallel -rx
        #mpiexec -n 4 ${MPI_OPTS} python -m pytest epyccel -v -m parallel -rx
        cd ..
      shell: bash
