name: 'Pyccel pytest commands generating fortran or c'
inputs:
  shell_cmd:
    description: 'Specifies the shell command (different for anaconda)'
    required: false
    default: "bash"


runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        #if [ -z ${{ runner.debug }} ]
        #then
        #  export DEBUG=1
        #  FLAGS="-s --log-cli-level DEBUG"
        #else
          FLAGS=""
        #fi
        which python
        python -m pytest -n auto -rXx -v -m "not (parallel or xdist_incompatible) and c" --ignore=symbolic --ignore=ndarrays ${FLAGS} -x
        if [ -n "${SITE_DIR}" ]; then
            echo "Touching"
            # Test ndarray folder update (requires parallel tests to avoid clean)
            touch ${SITE_DIR}/pyccel/stdlib/cwrapper/cwrapper.h
            python -m pytest -n auto -rXx -v -m c -k test_array_int32_1d_scalar epyccel/test_arrays.py ${FLAGS}
        fi
        python -m pytest -rXx -v -m "xdist_incompatible and not parallel and c" --ignore=symbolic --ignore=ndarrays ${FLAGS}
        pyccel-clean
        python -m pytest -n auto -rXx -v -m "not (parallel or xdist_incompatible) and not (c or python)" --ignore=symbolic --ignore=ndarrays ${FLAGS}
        python -m pytest -rXx -v -m "xdist_incompatible and not parallel and not (c or python)" --ignore=symbolic --ignore=ndarrays ${FLAGS}
        pyccel-clean
        python -m pytest ndarrays/ -rXx -v ${FLAGS}
        pyccel-clean
      shell: ${{ inputs.shell_cmd }}
      working-directory: ./tests
