# pylint: disable=missing-function-docstring, missing-module-docstring/
# ------------------------------- Strings ------------------------------------

print("mcha bba lsbata")
print('voilaaa')
print("3...2...1...Go!")
print('line1 \n line2\nline3')
print('\n', '\n')
print()
print("\nAZUL\n")
print("\nat\nmid\n")
print("'''''")
print("\"\'")
print('\'\'')
print("tab\ttab")
print("multistrings", "one", "two with\ttab", "   three     ")
print('\n')
print('\a')
print('\b')
print('\f')
print('\r')
print("'")
print('The last sentence.')
print('Preventing\tLine\nBreaks')
print('"walo" + "walo" == \'hiya walo\'.')
print('//\\//\/\/\\/\/\/\\/\/\\/\/\/\\/\/')
print("[^_^]")
print("[-_-]")
print("[+__+]")
print('[*-*]')
print("(0_0)")
print("mcha bba lsbata")
print("yan", "sin", "krad")
print('Azul', 'fellawn')
print("\b\v\b\v\b")
print("\a\b\n\b\f")
print('line1\nline2\nline3')
print('line1\rline2\rline3')
print("''''\"'\"\'///\\\\")
