name: 'Windows installation commands'

runs:
  using: "composite"
  steps:
    - name: Fix 'Unknown MS Compiler version 1900' problem
      continue-on-error: True
      run: |
        $PYTHON_EXE_PATH=(Get-Command python).Source
        $PYTHON_PATH=(Split-Path -Path ${PYTHON_EXE_PATH})
        # Use utf for output
        $PSDefaultParameterValues['Out-File:Encoding'] = 'Ascii'
        #
        sed '/return \[''msvcr100''\]/ a \        elif msc_ver == ''1900'':\\n            return [''msvcr140'']' ${PYTHON_PATH}\\Lib\\distutils\\cygwinccompiler.py > sed_tmp.py
        Move-Item -Path sed_tmp.py -Destination ${PYTHON_PATH}\\Lib\\distutils\\cygwinccompiler.py -Force
      shell: powershell
    - name: Check PATH
      run: |
        echo $PATH
      shell: bash
    - name: Check PATH
      run: |
          echo $env:PATH
      shell: powershell
    - name: Use MSys2 to install dependencies
      id: msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-cmake mingw-w64-x86_64-msmpi mingw-w64-x86_64-lapack m4 pkg-config
        path-type: inherit
    - name: Update to give Msys2 priority
      run: |
        MSYS2_ROOT=$(cygpath -m "${{ steps.msys2.outputs.msys2-location }}")
        echo "MSYS2_ROOT=$MSYS2_ROOT" >> $GITHUB_ENV
        echo "MSYS2_ROOT=$MSYS2_ROOT"
        echo $PATH
        echo $MSYS2_ROOT
        echo "$MSYS2_ROOT/mingw64/bin"
        echo "$MSYS2_ROOT/mingw64/bin" >> $GITHUB_PATH
        echo "$MSYS2_ROOT/usr/bin" >> $GITHUB_PATH
        cat $GITHUB_PATH
        ls /c/Miniconda/condabin
      shell: bash
    - name: Check PATH
      run: |
          echo $env:PATH
      shell: powershell
    - name: Check PATH
      run: |
        echo $PATH
      shell: bash
    - name: Add CC and FC to environment
      run: |
        GCC_EXE=$(which gcc)
        GFORTRAN_EXE=$(which gfortran)
        echo "CC=$GCC_EXE" >> $GITHUB_ENV
        echo "FC=$GFORTRAN_EXE" >> $GITHUB_ENV
        echo "CC=$GCC_EXE"
        echo "FC=$GFORTRAN_EXE"
        ls $MSYS2_ROOT/mingw64/bin
        echo $(which pkg-config)
        echo $(which pkg-config.exe)
      shell: bash
    - name: Update to give Msys2 priority
      run: |
        echo $PATH
        which pkg-config
        echo $(which pkg-config)
        echo $(which pkg-config.exe)
      shell: bash
    - name: Allow Python to find trusted DLLs
      run: |
        SITE_DIR=$(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')
        echo $SITE_DIR
        echo "import os; os.add_dll_directory('D:/a/_temp/msys64/mingw64/lib'); os.add_dll_directory('D:/a/_temp/msys64/mingw64/bin')" > $SITE_DIR/dll_path.pth
      shell: bash
    - name: Complete Microsoft MPI installation
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: msmpi
