name: 'Windows installation commands'

runs:
  using: "composite"
  steps:
    - name: Setup conda
      run: |
        choco install anaconda3
        source /c/tools/Anaconda3/etc/profile.d/conda.sh
        #source .travis/RefreshEnv.sh
        conda activate
        #
        # Change default C compiler from M$ to mingw in distutils.cfg
        echo -e "[build]\ncompiler = mingw32" >> /c/tools/Anaconda3/Lib/distutils/distutils.cfg
      shell: bash
    - name: Install Lapack
      run: |
        #
        # Download x64 BLAS and LAPACK DLLs from https://icl.cs.utk.edu/lapack-for-windows/lapack/
        WEB_ADDRESS=https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64
        LIBRARY_DIR=/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/lib
        curl $WEB_ADDRESS/libblas.dll -o $LIBRARY_DIR/libblas.dll
        curl $WEB_ADDRESS/liblapack.dll -o $LIBRARY_DIR/liblapack.dll
        #
        # Microsoft C runtime library: generate static libmsvcr140.a from vcruntime140.dll
        cd "$LIBRARY_DIR"
        cp $SYSTEMROOT/SysWOW64/vcruntime140.dll .
        gendef vcruntime140.dll
        dlltool -d vcruntime140.def -l libmsvcr140.a -D vcruntime140.dll
        cd -
      shell: bash
    - name: Install MS MPI runtime and SDK
      run: |
        #
        # Download MS MPI runtime and SDK
        curl -L https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe -o msmpisetup.exe
        curl -L https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisdk.msi -o msmpisdk.msi
        #
        # Install MS MPI
        ./msmpisetup.exe -unattend
        sleep 5
        msiexec //quiet //i msmpisdk.msi
      shell: bash
    - name: Setup MPI
      run: |
        #refreshenv
        export MSMPI_INC="C:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Include\\"
        export MSMPI_LIB64="C:\\Program Files (x86)\\Microsoft SDKs\\MPI\\Lib\\x64\\"
        export PATH=$PATH:"C:\\Program Files\\Microsoft MPI\\Bin"
        #
        # Generate mpi.mod for gfortran according to https://abhilashreddy.com/writing/3/mpi_instructions.html
        cd "$MSMPI_INC"
        sed -i 's/mpifptr.h/x64\/mpifptr.h/g' mpi.f90
        sed -i 's/mpifptr.h/x64\/mpifptr.h/g' mpif.h
        gfortran -c -D_WIN64 -D INT_PTR_KIND\(\)=8 -fno-range-check mpi.f90
        cd -
        #
        # Generate static libmsmpi.a from msmpi.dll
        cd "$MSMPI_LIB64"
        cp $SYSTEMROOT/SysWOW64/msmpi.dll .
        gendef msmpi.dll
        dlltool -d msmpi.def -l libmsmpi.a -D msmpi.dll
        cd -
      shell: bash
