name: 'Windows installation commands'

runs:
  using: "composite"
  steps:
    - name: Fix 'Unknown MS Compiler version 1900' problem
      continue-on-error: True
      run: |
        $PYTHON_EXE_PATH=(Get-Command python).Source
        $PYTHON_PATH=(Split-Path -Path ${PYTHON_EXE_PATH})
        # Use utf for output
        $PSDefaultParameterValues['Out-File:Encoding'] = 'Ascii'
        #
        sed '/return \[''msvcr100''\]/ a \        elif msc_ver == ''1900'':\\n            return [''msvcr140'']' ${PYTHON_PATH}\\Lib\\distutils\\cygwinccompiler.py > sed_tmp.py
        Move-Item -Path sed_tmp.py -Destination ${PYTHON_PATH}\\Lib\\distutils\\cygwinccompiler.py -Force
      shell: powershell
    - name: Use MSys2 to install dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-msmpi m4
    - name: Update PATH
      run: |
        which gcc
        which mpicc
        echo $PATH
        IFS=:
        for p in $PATH;
        do
          echo "PATH: $(cygpath -w $p)"
          echo $(cygpath -m $GITHUB_PATH)
          cygpath -w $p >> $(cygpath -m $GITHUB_PATH)
        done
      shell: msys2 {0}
    - name: Add CC and FC to environment
      run: |
        (Get-Command m4).Path
        $GCC_EXE=((Get-Command gcc).Path -replace '\\', '/')
        $GFORTRAN_EXE=((Get-Command gfortran).Path -replace '\\', '/')
        echo "CC=$GCC_EXE" >> $env:GITHUB_ENV
        echo "FC=$GFORTRAN_EXE" >> $env:GITHUB_ENV
        echo "CC=$GCC_EXE"
        echo "FC=$GFORTRAN_EXE"
      shell: powershell
