name: 'Coverage Setup'

runs:
  using: "composite"
  steps:
    - name: Installation
      run: |
        python -m pip install coverage
      shell: bash
    - name: Directory Creation
      run: |
        INSTALL_DIR=$(cd tests; python -c "import pyccel; print(pyccel.__path__[0])")
        SITE_DIR=$(dirname ${INSTALL_DIR})
        echo -e "import coverage; coverage.process_startup()" > ${SITE_DIR}/pyccel_cov.pth
        echo -e "[run]\nparallel = True\nsource = ${INSTALL_DIR}\ndata_file = $(pwd)/.coverage\n[report]\ninclude = ${INSTALL_DIR}/*\n[xml]\noutput = cobertura.xml" > .coveragerc
        echo "SITE_DIR=${SITE_DIR}" >> $GITHUB_ENV
        echo "COVERAGE_PROCESS_START=$(pwd)/.coveragerc" >> $GITHUB_ENV
      shell: bash
