name: 'Coverage Setup'

runs:
  using: "composite"
  steps:
    - name: Installation
      run: |
        python -m pip install coverage
        sudo apt-get install default-jre
      shell: bash
    - name: Directory Creation
        INSTALL_DIR=$(cd tests; python -c "import pyccel; print(pyccel.__path__[0])")
        SITE_DIR=$(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')
        echo -e "import coverage; coverage.process_startup()" > ${SITE_DIR}/pyccel_cov.pth
        echo -e "[run]\nparallel = True\nsource = ${INSTALL_DIR}\ndata_file = $(pwd)/.coverage\n[report]\ninclude = ${INSTALL_DIR}/*\n[xml]\noutput = cobertura.xml" > .coveragerc
        export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
      shell: bash
