


def acc_get_num_devices(anon_0 : 'int') -> 'int':
    ...

def acc_set_device_type(anon_0 : 'int') -> None:
    ...

def acc_get_device_type() -> 'int':
    ...

def acc_set_device_num(anon_0 : 'int', anon_1 : 'int') -> None:
    ...

def acc_get_device_num(anon_0 : 'int') -> 'int':
    ...

def acc_init(anon_0 : 'int') -> None:
    ...

def acc_shutdown(anon_0 : 'int') -> None:
    ...

def acc_async_test(anon_0 : 'bool') -> 'bool':
    ...

def acc_async_test_all() -> 'bool':
    ...

def acc_wait(anon_0 : 'bool') -> None:
    ...

def acc_wait_all(anon_0 : 'bool') -> None:
    ...

def acc_wait_async(anon_0 : 'bool', anon_1 : 'bool') -> None:
    ...

def acc_wait_all_async() -> None:
    ...

def acc_get_default_async() -> 'int':
    ...

def acc_set_default_async() -> None:
    ...

def acc_on_device(anon_0 : 'int') -> None:
    ...

def acc_malloc(anon_0 : 'int') -> 'int':
    ...

def acc_free(anon_0 : 'int') -> None:
    ...

def acc_map_data(anon_0 : 'Any', anon_1 : 'Any', anon_2 : 'int') -> None:
    ...

def acc_unmap_data(anon_0 : 'Any') -> None:
    ...

def acc_deviceptr(anon_0 : 'Any') -> 'int':
    ...

def acc_hostptr(anon_0 : 'Any') -> 'int':
    ...

def acc_memcpy_to_device(anon_0 : 'Any', anon_1 : 'Any', anon_2 : 'int') -> None:
    ...

def acc_memcpy_to_device_async(anon_0 : 'Any', anon_1 : 'Any', anon_2 : 'int', anon_3 : 'int') -> None:
    ...

def acc_memcpy_from_device(anon_0 : 'Any', anon_1 : 'Any', anon_2 : 'int') -> None:
    ...

def acc_memcpy_from_device_async(anon_0 : 'Any', anon_1 : 'Any', anon_2 : 'int', anon_3 : 'int') -> None:
    ...

def acc_memcpy_device(anon_0 : 'Any', anon_1 : 'Any', anon_2 : 'int') -> None:
    ...

def acc_memcpy_device_async(anon_0 : 'Any', anon_1 : 'Any', anon_2 : 'int', anon_3 : 'int') -> None:
    ...

