name: Bug report 🐞
description: File a bug report
title: "[Bug] "
labels: bug
body:
- type: checkboxes
  id: existing-issue
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: checkboxes
  id: changelog-check
  attributes:
    label: Is this issue mentioned in the CHANGELOG?
    description: Please search the [CHANGELOG](https://github.com/pyccel/pyccel/blob/devel/CHANGELOG.md) to see if the bug you encountered is already addressed in the upcoming release.
    options:
    - label: I have searched the CHANGELOG and expect the bug to be reproducible on the `devel` branch
      required: true

- type: textarea
  id: what-happened
  attributes:
    label: Describe the bug
    description: A concise description of what you are experiencing.
    placeholder: Tell us what you see!
  validations:
    required: true

- type: textarea
  id: expected-behaviour
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  id: screenshots
  attributes:
    label: Add Screenshots
    description: Add sufficient screenshots to explain your issue.

- type: checkboxes
  id: terms
  attributes:
    label: Record
    options:
    - label: "I have read the [Contributing Guidelines](https://github.com/pyccel/pyccel/blob/devel/docs/CONTRIBUTING.md)."
      required: true
    - label: "I have starred the repository"
      required: false
