name: Missing Coverage
description: Report untested code that needs investigation
title: 'COVERAGE:'
labels: [ 'internals' ]
assignees: []

body:
- type: textarea
  id: code-location
  attributes:
    label: Untested Code
    description: Provide the link to the untested code.
    placeholder: "https://github.com/pyccel/pyccel/blob/{COMMIT_SHA}/{file_location}#{line_numbers}"
  validations:
    required: true

- type: input
  id: pr-number
  attributes:
    label: PR Number
    description: Mention the PR where the issue was found.
    placeholder: "PR #X"
  validations:
    required: false

- type: textarea
  id: suggested-action
  attributes:
    label: Suggested Action
    description: Should a test be added, or should the code be removed?
    placeholder: "Explain your reasoning..."
  validations:
    required: true
