name: Installation Problem
description: Report an issue encountered during installation
title: ''
labels: [ 'bug' ]
assignees: []

body:
- type: markdown
  attributes:
    value: |
      ## Relevant Discussion  
      Most installation problems are related to dependencies rather than Pyccel itself.  
      Please link to a discussion in the [Q&A section](https://github.com/pyccel/pyccel/discussions/categories/q-a) where the problem was investigated.

- type: textarea
  id: description
  attributes:
    label: Problem Description
    description: Provide a clear and concise description of the problem encountered.
  validations:
    required: true

- type: input
  id: python-version
  attributes:
    label: Python Version
    description: Enter the Python version you are using (e.g., 3.9.7).
  validations:
    required: true

- type: input
  id: os-version
  attributes:
    label: OS Version
    description: Enter your operating system version (e.g., Ubuntu 22.04, Windows 11).
  validations:
    required: true

- type: textarea
  id: dependencies
  attributes:
    label: Dependency Versions
    description: List versions of any relevant dependencies (e.g., NumPy, SciPy). You can paste the output of `pip freeze` here.
