SET(CMAKE_Fortran_COMPILER "/usr/bin/gfortran" CACHE FILEPATH " " FORCE)
SET(MPI_Fortran_COMPILER   "/softs/cemracs/petsc/3.5.1/arch-linux2-c-debug/bin/mpif90" CACHE FILEPATH " " FORCE)
SET(PETSC_ARCH             "arch-linux2-c-debug" CACHE STRING   " " FORCE)
SET(PETSC_DIR              "/softs/cemracs/petsc/3.5.1" CACHE PATH  " " FORCE)
SET(PYTHON_EXECUTABLE      "/softs/Python/2.7.3/bin/python" CACHE FILEPATH " " FORCE)
