name: 'Pyccel pytest commands running parallel tests'
inputs:
  shell_cmd:
    description: 'Specifies the shell command (different for anaconda)'
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        mpiexec -n 4 ${MPI_OPTS} pytest --with-mpi -ra -v epyccel/test_parallel_epyccel.py
        #mpiexec -n 4 ${MPI_OPTS} pytest --with-mpi -ra -v epyccel
      shell: ${{ inputs.shell_cmd }}
      working-directory: ./tests

