name: 'Pyccel pytest commands running parallel tests'

runs:
  using: "composite"
  steps:
    - name: Test with pytest
      run: |
        mpiexec -n 4 ${MPI_OPTS} python -m pytest epyccel/test_parallel_epyccel.py -v -m parallel -rx
        #mpiexec -n 4 ${MPI_OPTS} python -m pytest epyccel -v -m parallel -rx
      shell: bash
      working-directory: ./tests

