# from math import (inf, nan)


# print()
print(42)
# print(3.14)
# print(5.00000)
# print(78.494984)
# print(inf)
# print(nan)
# print(1 + 2j)
# print(True)
# print(1, 2, 3, "mcha bba lsbata")
# print("yan", "sin", "krad")
print('voilaaa')
# # print(None)
# print("3...2...1...Go!")
# print('Azul', 'fellawn', sep=None)
# print('ahoy', 'world', sep=' ')
# print('ohoy', 'awa', sep='')
# print('bonjour', 'Le monde', sep='\n')
# print('home', 'user', 'documents', sep='/')
# print('', 'home', 'user', 'documents', sep='/')
# print(1, 'Python Tricks', 'Dan Bader', sep=',')
# print('node', 'child', 'child', sep=' -> ')
# print('line1\nline2\nline3')
# print('line1\r\nline2\r\nline3')
# print('The first sentence', end='. ')
# print('The second sentence', end='. ')
# print('The last sentence.')
# print('Mercury', 'Venus', 'Earth', sep=', ', end=', ')
# print('Mars', 'Jupiter', 'Saturn', sep=', ', end=', ')
# print('Uranus', 'Neptune', 'Pluto', sep=', ')
# print('Printing in a Nutshell', end='\n * ')
# print('Calling Print', end='\n * ')
# print('Separating Multiple Arguments', end='\n * ')
# print('Preventing Line Breaks')
# print('//\\//\/\/\\/\/\/\\/\/\\/\/\/\\/\/')
# print('"walo" + "walo" == \'hiya walo\'.')
# print("[^_^]")
# print("[-_-]")
# print("[+ __ +]")
# print("[~_~]", "lem3efer")
# print('[*-*]')
# print("(0_0)")
