# pylint: disable=missing-function-docstring, missing-module-docstring
import json
import os
import platform
import random
import re
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pluggy
import pytest
from filelock import FileLock

from pyccel.ast.utilities import python_builtin_libs
from pyccel.codegen.pipeline import execute_pyccel
from pyccel.compilers.default_compilers import available_compilers

# ==============================================================================
# UTILITIES
# ==============================================================================


def get_abs_path(relative_path):
    base_dir = Path(__file__).resolve().parent
    return base_dir / relative_path


# ------------------------------------------------------------------------------


def get_thread_local_subdir(dirname=get_abs_path("")):
    return dirname / f"__pyccel__{os.environ.get('PYTEST_XDIST_WORKER', '')}"


# ------------------------------------------------------------------------------
def copy_to_isolated_dir(isolated_dir, base_dir, rel_path):
    """
    Copy a file into a shared isolated directory.

    Copy the file at `rel_path` (relative to this file's folder) into
    `isolated_dir`, preserving its path relative to `base_dir`. All files
    belonging to the same test must be copied with the same `isolated_dir`/
    `base_dir` pair so that they land next to each other and relative/package
    imports between them keep working. Any `__init__.py` package markers
    found between `base_dir` and `rel_path` are copied too.

    Parameters
    ----------
    isolated_dir : Path
        The directory (exclusive to the current test) into which files
        should be copied.

    base_dir : str/Path
        The directory, relative to the folder containing this file, that
        `rel_path` (and every other file copied alongside it) is nested
        under. Used to compute the destination path inside `isolated_dir`.

    rel_path : str/Path
        The path of the file to copy, relative to the folder containing
        this file.

    Returns
    -------
    Path
        The absolute path of the copy, inside `isolated_dir`.
    """
    rel_path = Path(rel_path)
    base_dir = Path(base_dir)
    rel_to_base = rel_path.relative_to(base_dir)

    for ancestor in rel_to_base.parents:
        src_init = get_abs_path(base_dir / ancestor / "__init__.py")
        if src_init.is_file():
            dst_init = isolated_dir / ancestor / "__init__.py"
            if not dst_init.is_file():
                dst_init.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy(src_init, dst_init)

    dst = isolated_dir / rel_to_base
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(get_abs_path(rel_path), dst)
    return dst


# ------------------------------------------------------------------------------
def get_exe(filename, language=None):
    filename = Path(filename)
    if language != "python":
        exefile1 = filename.with_suffix("")
        if sys.platform == "win32":
            exefile1 = exefile1.with_suffix(".exe")
    else:
        exefile1 = filename

    return exefile1


# ------------------------------------------------------------------------------
def insert_pyccel_folder(abs_path):
    abs_path = Path(abs_path)
    return get_thread_local_subdir(abs_path.parent) / abs_path.name


# ------------------------------------------------------------------------------
def get_python_output(abs_path, cwd=None):
    assert abs_path.is_absolute()
    p = subprocess.run(
        [sys.executable, abs_path], text=True, capture_output=True, check=True, cwd=cwd
    )
    return p.stdout


# ------------------------------------------------------------------------------
def compile_pyccel(path_dir, test_file, options=""):
    if "python" in options and "--output" not in options:
        options += " --output=__pyccel__"
    cmd = [shutil.which("pyccel"), "compile", test_file]
    if options != "":
        cmd += options.strip().split()
    p = subprocess.Popen(cmd, universal_newlines=True, cwd=path_dir)
    p.wait()
    assert p.returncode == 0


# ------------------------------------------------------------------------------
def compile_c(path_dir, test_file, generated_file, generated_dependencies, is_mod=False):
    """
    Compile C code manually.

    Compile C code manually. This is a wrapper around compile_fortran_or_c.

    Parameters
    ----------
    path_dir : str
        The path to the directory where the compilation command should be run from.

    test_file : str
        The Python file which was translated. Used only to determine the
        name/location of the output executable.

    generated_file : Path
        The path, in its final folder, of the C file generated by pyccel
        from `test_file`.

    generated_dependencies : list of Path
        A list of the C files, in their final folders, generated by pyccel
        from the Python dependencies of the file.

    is_mod : bool, default=False
        True if translating a module, False if translating a program

    See also
    --------
    compile_fortran_or_c : The function that is called.
    """
    compiler_family = os.environ.get("PYCCEL_DEFAULT_COMPILER", "GNU")
    compiler_info = available_compilers[compiler_family]["c"]
    compiler = compiler_info["exec"]
    folder = generated_file.parent
    deps = []
    subfolders = [f for f in folder.iterdir() if f.is_dir()]
    for f in subfolders:
        for fi in f.iterdir():
            if fi.suffix == ".c":
                deps.append(f / (fi.with_suffix(".py")))
                subprocess.run(
                    [compiler, "-c", fi.name, "-o", fi.stem + ".o"], cwd=f, check=True
                )
    compile_fortran_or_c(
        compiler_info,
        path_dir,
        test_file,
        generated_file,
        generated_dependencies,
        deps,
        is_mod,
    )


# ------------------------------------------------------------------------------
def compile_fortran(
    path_dir, test_file, generated_file, generated_dependencies, is_mod=False
):
    """
    Compile Fortran code manually.

    Compile Fortran code manually. This is a wrapper around compile_fortran_or_c.

    Parameters
    ----------
    path_dir : str
        The path to the directory where the compilation command should be run from.

    test_file : str
        The Python file which was translated. Used only to determine the
        name/location of the output executable.

    generated_file : Path
        The path, in its final folder, of the Fortran file generated by
        pyccel from `test_file`.

    generated_dependencies : list of Path
        A list of the Fortran files, in their final folders, generated by
        pyccel from the Python dependencies of the file.

    is_mod : bool, default=False
        True if translating a module, False if translating a program

    See also
    --------
    compile_fortran_or_c : The function that is called.
    """
    compiler_family = os.environ.get("PYCCEL_DEFAULT_COMPILER", "GNU")
    compiler_info = available_compilers[compiler_family]["fortran"]
    compile_fortran_or_c(
        compiler_info,
        path_dir,
        test_file,
        generated_file,
        generated_dependencies,
        (),
        is_mod,
    )


# ------------------------------------------------------------------------------
def compile_fortran_or_c(
    compiler_info,
    path_dir,
    test_file,
    generated_file,
    dependencies,
    std_deps,
    is_mod=False,
):
    """
    Compile Fortran or C code manually.

    Compile Fortran or C code manually. This is necessary when support is missing for the
    wrapper or when dependencies also need to be translated and compiled.

    Parameters
    ----------
    compiler_info : dict
        A dictionary describing the compiler properties.

    path_dir : str
        The path to the directory where the compilation command should be run from.

    test_file : str
        The Python file which was translated. Used only to determine the
        name/location of the output executable.

    generated_file : Path
        The path, in its final folder, of the Fortran/C file (already carrying
        its .c/.f90 extension) generated by pyccel from `test_file`.

    dependencies : list of Path
        A list of the Fortran/C files (already carrying their .c/.f90
        extension), in their final folders, generated by pyccel from the
        Python dependencies of the file.

    std_deps : list of str
        A list of any language-specific dependencies of the file (e.g. ndarrays).

    is_mod : bool, default=False
        True if translating a module, False if translating a program
    """
    compiler = compiler_info["exec"]
    extension = generated_file.suffix
    root = generated_file.with_suffix("")

    assert generated_file.is_file()

    deps = list(dependencies)
    base_dir = root.parent
    if not is_mod:
        prog_root = base_dir / ("prog_" + root.name)
        if prog_root.with_suffix(extension).is_file():
            compile_fortran_or_c(
                compiler_info,
                path_dir,
                test_file,
                generated_file,
                dependencies,
                std_deps,
                is_mod=True,
            )
            root = prog_root
            deps.append(generated_file)

    if is_mod:
        command = [shutil.which(compiler), "-c", str(root.with_suffix(extension))]
        for d in deps:
            command.append("-I" + str(d.parent))
        for d in std_deps:
            command.append("-I" + str(Path(d).parent))
    else:
        command = [compiler, "-O3", str(root.with_suffix(extension))]
        for d in deps:
            command.append(str(d.with_suffix(".o")))
            command.append("-I" + str(d.parent))
        for d in std_deps:
            command.append(str(Path(d).with_suffix(".o")))
            command.append("-I" + str(Path(d).parent))
    command.append("-I" + str(base_dir))

    command.append("-o")
    if is_mod:
        command.append(f"{root}.o")
    else:
        command.append(get_exe(test_file))

    if "module_output_flag" in compiler_info:
        command.append(compiler_info["module_output_flag"])
        command.append(base_dir)

    subprocess.run(command, cwd=path_dir, check=True)


# ------------------------------------------------------------------------------
def get_lang_output(abs_path, language):
    abs_path = get_exe(abs_path, language)
    if language == "python":
        return get_python_output(abs_path)
    else:
        p = subprocess.run([abs_path], text=True, capture_output=True, check=True)
        return p.stdout


# ------------------------------------------------------------------------------
def get_value(string, regex, conversion):
    match = regex.search(string)
    assert match
    value = conversion(match.group())
    string = string[match.span()[1] :]
    return value, string


def compare_pyth_fort_output_by_type(p_output, f_output, dtype=float, language=None):

    if dtype is str:
        p_output_split = re.split("\n", p_output)
        f_output_split = re.split("\n", f_output)
        p_list = p_output_split[0].strip()
        f_list = f_output_split[0].strip()
        p_output = "\n".join(p_output_split[1:])
        f_output = "\n".join(f_output_split[1:])
        assert p_list == f_list
    elif dtype is complex:
        rx = re.compile("-?[0-9.]+([eE][+-]?[0-9]+)?j?")
        p, p_output = get_value(p_output, rx, complex)
        if p.imag == 0:
            p2, p_output = get_value(p_output, rx, complex)
            p = p + p2
        if language == "python":
            f, f_output = get_value(f_output, rx, complex)
            if f.imag == 0:
                f2, f_output = get_value(f_output, rx, complex)
                f = f + f2
        else:
            rx = re.compile("-?[0-9.]+([eE][+-]?[0-9]+)?")
            f, f_output = get_value(f_output, rx, float)
            f2, f_output = get_value(f_output, rx, float)
            f = f + f2 * 1j
        assert np.isclose(p, f)
    elif dtype is bool:
        rx = re.compile("TRUE|True|true|1|T|t|FALSE|False|false|F|f|0")
        bool_conversion = lambda m: m.lower() in ["true", "t", "1"]
        p, p_output = get_value(p_output, rx, bool_conversion)
        f, f_output = get_value(f_output, rx, bool_conversion)
        assert p == f

    elif dtype is float:
        rx = re.compile("-?[0-9.]+([eE][+-]?[0-9]+)?")
        p, p_output = get_value(p_output, rx, float)
        f, f_output = get_value(f_output, rx, float)
        assert np.isclose(p, f)

    elif dtype is int:
        rx = re.compile("-?[0-9]+([eE][+-]?[0-9]+)?")
        p, p_output = get_value(p_output, rx, int)
        f, f_output = get_value(f_output, rx, int)
        assert p == f
    else:
        raise NotImplementedError("Type comparison not implemented")
    return p_output, f_output


# ------------------------------------------------------------------------------
def compare_pyth_fort_output(p_output, f_output, dtype=float, language=None):

    if isinstance(dtype, list):
        for d in dtype:
            p_output, f_output = compare_pyth_fort_output_by_type(
                p_output, f_output, d, language=language
            )
    elif dtype is complex:
        while len(p_output) > 0 and len(f_output) > 0:
            p_output, f_output = compare_pyth_fort_output_by_type(
                p_output, f_output, complex, language=language
            )
    elif dtype is str:
        compare_pyth_fort_output_by_type(p_output, f_output, dtype)
    else:
        p_output = p_output.strip().split()
        f_output = f_output.strip().split()
        for p, f in zip(p_output, f_output):
            compare_pyth_fort_output_by_type(p, f, dtype)


# ------------------------------------------------------------------------------
def pyccel_test(
    test_file,
    dependencies=None,
    compile_with_pyccel=True,
    cwd=None,
    pyccel_commands="",
    output_dtype=float,
    language=None,
    *,
    isolated_dir,
):
    """
    Run pyccel and compare the output to ensure that the results
    are equivalent

    Parameters
    ----------
    test_file : str
                The name of the file containing the program.
                The path must either be absolute or relative
                to the folder containing this file
    dependencies : str/list
                The name of any files which are called by the
                test_file and must therefore be pyccelized in
                order to run it
                The paths must either be absolute or relative
                to the folder containing this file
    compile_with_pyccel : bool
                Indicates whether the compilation step should
                be handled by a basic call to gfortran/gcc (False)
                or internally by pyccel (True)
                default : True
    cwd : str
                The directory from which pyccel and other executables
                will be called
                default : The folder containing the test_file
    pyccel_commands : str
                Any additional commands which should be passed to
                pyccel
    output_dtype : type/list of types
                The types expected as output of the program.
                If one argument is provided then all types are
                assumed to be the same
    language : str
                The language pyccel should translate to
                default = 'fortran'
    isolated_dir : Path
                The test-exclusive directory (typically pytest's
                `tmp_path` fixture) into which test files are copied
                and pyccel is run
    """

    test_file = Path(test_file)
    rel_test_dir = test_file.parent

    if cwd is None:
        rel_cwd = rel_test_dir
    else:
        cwd = Path(cwd)
        rel_cwd = cwd.relative_to(get_abs_path("")) if cwd.is_absolute() else cwd

    pyth_out = get_python_output(get_abs_path(test_file), get_abs_path(rel_cwd))

    if language:
        pyccel_commands += " --language=" + language
    else:
        language = "fortran"

    test_file = copy_to_isolated_dir(isolated_dir, rel_test_dir, test_file)
    cwd = isolated_dir / rel_cwd.relative_to(rel_test_dir)
    output_dir = isolated_dir / "__pyccel__" if language == "python" else None

    if dependencies:
        if isinstance(dependencies, str):
            dependencies = [dependencies]
        for i, d in enumerate(dependencies):
            d = Path(d)
            if output_dir:
                rel_path = d.parent.relative_to(rel_test_dir)
                output = output_dir / rel_path
                pyc_command = pyccel_commands + " --output={}".format(output)
            else:
                pyc_command = pyccel_commands

            dependencies[i] = copy_to_isolated_dir(isolated_dir, rel_test_dir, d)

            if not compile_with_pyccel:
                compile_pyccel(cwd, dependencies[i], pyc_command + " -t")
                if language == "fortran":
                    generated_dep = insert_pyccel_folder(dependencies[i]).with_suffix(
                        ".f90"
                    )
                    compile_fortran(cwd, dependencies[i], generated_dep, [], is_mod=True)
                elif language == "c":
                    generated_dep = insert_pyccel_folder(dependencies[i]).with_suffix(
                        ".c"
                    )
                    compile_c(cwd, dependencies[i], generated_dep, [], is_mod=True)
            else:
                compile_pyccel(cwd, dependencies[i], pyc_command)

    if output_dir:
        pyccel_commands += " --output " + str(output_dir)
        output_test_file = output_dir / test_file.name
    else:
        output_test_file = test_file

    if compile_with_pyccel:
        compile_pyccel(cwd, test_file, pyccel_commands)
    else:
        compile_pyccel(cwd, test_file, pyccel_commands + " -t")
        if not dependencies:
            dependencies = []
        if language == "fortran":
            generated_file = insert_pyccel_folder(output_test_file).with_suffix(".f90")
            generated_dependencies = [
                insert_pyccel_folder(d).with_suffix(".f90") for d in dependencies
            ]
            compile_fortran(cwd, output_test_file, generated_file, generated_dependencies)
        elif language == "c":
            generated_file = insert_pyccel_folder(output_test_file).with_suffix(".c")
            generated_dependencies = [
                insert_pyccel_folder(d).with_suffix(".c") for d in dependencies
            ]
            compile_c(cwd, output_test_file, generated_file, generated_dependencies)

    lang_out = get_lang_output(output_test_file, language)
    compare_pyth_fort_output(pyth_out, lang_out, output_dtype, language)


# ==============================================================================
# UNIT TESTS
# ==============================================================================
def test_relative_imports_in_project(language, tmp_path):

    base_dir = Path(__file__).parent
    path_dir = base_dir / "project_rel_imports"
    dependencies = [
        "project_rel_imports/project/folder1/mod1.py",
        "project_rel_imports/project/folder2/mod2.py",
        "project_rel_imports/project/folder2/mod3.py",
    ]
    pyccel_test(
        "project_rel_imports/runtest.py",
        dependencies,
        cwd=path_dir,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_absolute_imports_in_project(language, tmp_path):

    base_dir = Path(__file__).parent
    path_dir = base_dir / "project_abs_imports"
    dependencies = [
        "project_abs_imports/project/folder1/mod1.py",
        "project_abs_imports/project/folder2/mod2.py",
        "project_abs_imports/project/folder2/mod3.py",
    ]
    pyccel_test(
        "project_abs_imports/runtest.py",
        dependencies,
        cwd=path_dir,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_rel_imports_python_accessible_folder(language):
    # pyccel is called on scripts/folder2/runtest_rel_imports.py from the scripts folder
    # From this folder python understands relative imports
    from scripts.folder2.runtest_rel_imports import test_func

    pyth_out = str(test_func())

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("."))
    copy_to_isolated_dir(isolated_dir, ".", "run_import_function.py")
    copy_to_isolated_dir(isolated_dir, ".", "scripts/folder2/folder2_funcs.py")
    test_file = copy_to_isolated_dir(
        isolated_dir, ".", "scripts/folder2/runtest_rel_imports.py"
    )
    path_dir = isolated_dir / "scripts"
    tmp_dir = isolated_dir / "__pyccel__"

    pyccel_opt = "--language={}".format(language)
    if language == "python":
        pyccel_opt += " --output={}".format(tmp_dir / "folder2")
    compile_pyccel(
        path_dir / "folder2",
        isolated_dir / "scripts/folder2/folder2_funcs.py",
        pyccel_opt,
    )
    compile_pyccel(path_dir, test_file, pyccel_opt)
    if language == "python":
        test_location = "__pyccel__.folder2.runtest_rel_imports"
    else:
        test_location = "scripts.folder2.runtest_rel_imports"
    p = subprocess.run(
        [
            sys.executable,
            str(isolated_dir / "run_import_function.py"),
            test_location,
        ],
        text=True,
        capture_output=True,
        check=True,
    )
    fort_out = p.stdout

    compare_pyth_fort_output(pyth_out, fort_out)


# ------------------------------------------------------------------------------
def test_multi_imports_project(language, tmp_path):

    base_dir = Path(__file__).parent
    path_dir = base_dir / "project_multi_imports"
    dependencies = [
        "project_multi_imports/file1.py",
        "project_multi_imports/file2.py",
        "project_multi_imports/file3.py",
    ]
    pyccel_test(
        "project_multi_imports/file4.py",
        dependencies,
        cwd=path_dir,
        language=language,
        output_dtype=str,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_imports_compile(language, tmp_path):
    pyccel_test(
        "scripts/runtest_imports.py",
        "scripts/funcs.py",
        compile_with_pyccel=False,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_imports_in_folder(language, tmp_path):
    pyccel_test(
        "scripts/runtest_folder_imports.py",
        "scripts/folder1/folder1_funcs.py",
        compile_with_pyccel=False,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_imports(language, tmp_path):
    pyccel_test(
        "scripts/runtest_imports.py",
        "scripts/funcs.py",
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_folder_imports(language):
    # pyccel is called on scripts/folder2/runtest_imports2.py from the scripts/folder2 folder
    # which is where the final .so file should be
    # From this folder python doesn't understand relative imports
    from scripts.folder2.runtest_imports2 import test_func

    pyth_out = str(test_func())

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("."))
    copy_to_isolated_dir(isolated_dir, ".", "run_import_function.py")
    copy_to_isolated_dir(isolated_dir, ".", "scripts/folder1/folder1_funcs.py")
    copy_to_isolated_dir(isolated_dir, ".", "scripts/folder2/runtest_imports2.py")
    path_dir = isolated_dir / "scripts"
    tmp_dir = isolated_dir / "__pyccel__"

    language_opt = "--language={}".format(language)
    pyccel_opt = language_opt
    if language == "python":
        pyccel_opt = language_opt + " --output={}".format(tmp_dir / "folder1")
    compile_pyccel(
        path_dir / "folder1",
        isolated_dir / "scripts/folder1/folder1_funcs.py",
        pyccel_opt,
    )
    if language == "python":
        pyccel_opt = language_opt + " --output={}".format(tmp_dir / "folder2")
    compile_pyccel(
        path_dir / "folder2",
        isolated_dir / "scripts/folder2/runtest_imports2.py",
        pyccel_opt,
    )

    if language == "python":
        test_location = "__pyccel__.folder2.runtest_imports2"
    else:
        test_location = "scripts.folder2.runtest_imports2"
    p = subprocess.run(
        [
            sys.executable,
            str(isolated_dir / "run_import_function.py"),
            test_location,
        ],
        text=True,
        capture_output=True,
        check=True,
    )
    fort_out = p.stdout

    compare_pyth_fort_output(pyth_out, fort_out)


# ------------------------------------------------------------------------------
def test_funcs(language, tmp_path):
    pyccel_test("scripts/runtest_funcs.py", language=language, isolated_dir=tmp_path)


def test_capitalised_language(language):
    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts"))
    test_file = copy_to_isolated_dir(
        isolated_dir, "scripts", "scripts/runtest_funcs.py"
    )
    cwd = test_file.parent
    output_folder = isolated_dir / "__pyccel__"
    compile_pyccel(
        cwd, test_file, f"--language={language.capitalize()} --output={output_folder}"
    )


# ------------------------------------------------------------------------------
# Enumerate not supported in c
def test_inout_func(language, tmp_path):
    pyccel_test(
        "scripts/runtest_inoutfunc.py", language=language, isolated_dir=tmp_path
    )


# ------------------------------------------------------------------------------
def test_bool(language, tmp_path):
    pyccel_test(
        "scripts/bool_comp.py",
        output_dtype=bool,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_expressions(experimental_language, tmp_path):
    types = (
        [float, complex, int, float, float, int]
        + [float] * 3
        + [complex, int, complex, complex, int, int, float]
        + [complex] * 3
        + [float] * 3
        + [int]
        + [float] * 2
        + [int]
        + [float] * 3
        + [int]
        + [float] * 3
        + [int] * 2
        + [float] * 2
        + [int] * 5
        + [complex]
        + [bool] * 9
    )
    pyccel_test(
        "scripts/expressions.py",
        language=experimental_language,
        output_dtype=types,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.fortran
def test_generic_functions(tmp_path):
    # Only testing Fortran for simple compilation outside of Pyccel
    pyccel_test(
        "scripts/runtest_generic_functions.py",
        dependencies="scripts/generic_functions.py",
        compile_with_pyccel=False,
        output_dtype=[
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            int,
            float,
            int,
            int,
        ],
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_default_arguments(language, tmp_path):
    pyccel_test(
        "scripts/runtest_default_args.py",
        dependencies="scripts/default_args_mod.py",
        output_dtype=[
            int,
            int,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            bool,
            bool,
            bool,
            float,
            float,
            float,
            float,
            int,
            int,
            float,
            float,
            float,
            float,
        ],
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_pyccel_calling_directory(language):
    pyth_out = get_python_output(get_abs_path("scripts/runtest_funcs.py"))

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("."))
    test_file = copy_to_isolated_dir(isolated_dir, ".", "scripts/runtest_funcs.py")
    cwd = isolated_dir

    language_opt = "--language={}".format(language)
    compile_pyccel(cwd, test_file, language_opt)

    if language == "python":
        test_file = isolated_dir / "__pyccel__" / test_file.name
    fort_out = get_lang_output(test_file, language)

    compare_pyth_fort_output(pyth_out, fort_out)


# ------------------------------------------------------------------------------
def test_in_specified(language, tmp_path):
    pyccel_test(
        "scripts/runtest_degree_in.py", language=language, isolated_dir=tmp_path
    )


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/hope_benchmarks/fib.py",
        "scripts/hope_benchmarks/quicksort.py",
        "scripts/hope_benchmarks/hope_pisum.py",
        "scripts/hope_benchmarks/hope_ln_python.py",
        "scripts/hope_benchmarks/hope_pairwise_python.py",
        "scripts/hope_benchmarks/point_spread_func.py",
        "scripts/hope_benchmarks/simplify.py",
    ],
)
def test_hope_benchmarks(test_file, language, tmp_path):
    pyccel_test(test_file, language=language, isolated_dir=tmp_path)


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/import_syntax/from_mod_import.py",
        "scripts/import_syntax/from_mod_import_as.py",
        "scripts/import_syntax/import_mod.py",
        "scripts/import_syntax/import_mod_as.py",
        "scripts/import_syntax/from_mod_import_func.py",
        "scripts/import_syntax/from_mod_import_as_func.py",
        "scripts/import_syntax/import_mod_func.py",
        "scripts/import_syntax/import_mod_as_func.py",
        "scripts/import_syntax/collisions3.py",
        "scripts/import_syntax/collisions5.py",
    ],
)
def test_import_syntax(test_file, language, tmp_path):
    pyccel_test(test_file, language=language, isolated_dir=tmp_path)


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/import_syntax/from_mod_import_as_user_func.py",
        "scripts/import_syntax/from_mod_import_as_user.py",
        "scripts/import_syntax/collisions2.py",
        "scripts/runtest_import_mod_project_as.py",
    ],
)
def test_import_syntax_user_as(test_file, language, tmp_path):
    pyccel_test(
        test_file,
        dependencies="scripts/import_syntax/user_mod.py",
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/import_syntax/from_mod_import_user.py",
        "scripts/import_syntax/import_mod_user.py",
        "scripts/import_syntax/import_mod_as_user.py",
        "scripts/import_syntax/from_mod_import_user_func.py",
        "scripts/import_syntax/import_mod_user_func.py",
        "scripts/import_syntax/import_mod_as_user_func.py",
    ],
)
def test_import_syntax_user(test_file, language, tmp_path):
    pyccel_test(
        test_file,
        dependencies="scripts/import_syntax/user_mod.py",
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_import_collisions(language, tmp_path):
    pyccel_test(
        "scripts/import_syntax/collisions4.py",
        dependencies=[
            "scripts/import_syntax/user_mod.py",
            "scripts/import_syntax/user_mod2.py",
        ],
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_import_collisions_builtins(language, tmp_path):
    pyccel_test(
        "scripts/import_syntax/collisions6.py",
        dependencies=["scripts/import_syntax/user_mod_builtin_conflict.py"],
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_class_import_as(language, tmp_path):
    pyccel_test(
        "scripts/import_syntax/from_cls_mod_import_as_user.py",
        dependencies=["scripts/import_syntax/user_cls_mod.py"],
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
# Numpy sum required
@pytest.mark.parametrize(
    "language",
    (
        pytest.param("fortran", marks=pytest.mark.fortran),
        pytest.param("python", marks=pytest.mark.python),
    ),
)
def test_numpy_kernels_compile(language):
    pyccel_opt = "--language={}".format(language)
    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts/numpy"))
    test_file = copy_to_isolated_dir(
        isolated_dir, "scripts/numpy", "scripts/numpy/numpy_kernels.py"
    )
    compile_pyccel(isolated_dir, test_file, pyccel_opt)


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "language",
    (
        pytest.param("fortran", marks=pytest.mark.fortran),
        pytest.param("python", marks=pytest.mark.python),
    ),
)
def test_randint_size_program(language, tmp_path):
    pyccel_test(
        "scripts/numpy/randint_size.py", language=language, isolated_dir=tmp_path
    )


# ------------------------------------------------------------------------------
def test_multiple_results(language, tmp_path):
    pyccel_test(
        "scripts/runtest_multiple_results.py",
        output_dtype=[
            int,
            float,
            complex,
            bool,
            int,
            complex,
            int,
            bool,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            float,
            int,
            int,
        ],
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_elemental(language, tmp_path):
    pyccel_test(
        "scripts/decorators_elemental.py", language=language, isolated_dir=tmp_path
    )


# ------------------------------------------------------------------------------
def test_print_strings(experimental_language, tmp_path):
    types = str
    pyccel_test(
        "scripts/print_strings.py",
        language=experimental_language,
        output_dtype=types,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "language",
    (
        pytest.param("python", marks=pytest.mark.python),
        pytest.param("c", marks=pytest.mark.c),
        pytest.param(
            "fortran",
            marks=[
                pytest.mark.skip(reason="Can't print NaN in Fortran"),
                pytest.mark.fortran,
            ],
        ),
    ),
)
def test_print_nan(language, tmp_path):
    types = str
    pyccel_test(
        "scripts/print_nan.py",
        language=language,
        output_dtype=types,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_print_integers(language, tmp_path):
    types = str
    pyccel_test(
        "scripts/print_integers.py",
        language=language,
        output_dtype=types,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_print_sp_and_end(experimental_language, tmp_path):
    types = str
    pyccel_test(
        "scripts/print_sp_and_end.py",
        language=experimental_language,
        output_dtype=types,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_c_arrays(language, tmp_path):
    types = (
        [int] * 15
        + [float] * 5
        + [int] * 25
        + [float] * 20 * 5
        + [complex] * 3 * 10
        + [complex] * 5
        + [float] * 10
        + [float] * 6
        + [float] * 2 * 3
        + [complex] * 3 * 10
        + [float] * 2 * 3
        + [int] * 3
    )
    pyccel_test(
        "scripts/c_arrays.py",
        language=language,
        output_dtype=types,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "language",
    (
        pytest.param("fortran", marks=pytest.mark.fortran),
        pytest.param("python", marks=pytest.mark.python),
        pytest.param(
            "c",
            marks=[
                pytest.mark.xfail(reason="Negative slices are not handled"),
                pytest.mark.c,
            ],
        ),
    ),
)
def test_arrays_view(language, tmp_path):
    types = (
        [int] * 10
        + [int] * 10
        + [int] * 4
        + [int] * 4
        + [int] * 10
        + [int] * 6
        + [int] * 10
        + [int] * 10
        + [int] * 25
        + [int] * 60
    )
    if platform.system() in ("Darwin", "Windows") and language == "fortran":
        # MacOS compiler incorrectly reports
        # Fortran runtime error: Index '4378074096' of dimension 2 of array 'a' outside of expected range (0:2)
        # At line 208 of file /Users/runner/work/pyccel/pyccel/tests/pyccel/scripts/__pyccel__/arrays_view.f90
        # x(0:) => a(1_i64:, merge(3_i64 + v, v, v < 0_i64))
        pyccel_test(
            "scripts/arrays_view.py",
            language=language,
            output_dtype=types,
            pyccel_commands="--no-debug",
            isolated_dir=tmp_path,
        )
    else:
        pyccel_test(
            "scripts/arrays_view.py",
            language=language,
            output_dtype=types,
            isolated_dir=tmp_path,
        )


# ------------------------------------------------------------------------------
def test_return_numpy_arrays(language, tmp_path):
    types = [int] * 4  # 4 ints for a
    types += [int] * 2  # 2 ints for b
    types += [float] * 2  # 2 floats for c
    types += [bool] * 2  # 2 bools for d
    types += [complex] * 2  # 2 complexes for e
    types += [float] * 5  # 5 floats for h
    types += [int] * 5  # 5 ints for g
    types += [int] * 4  # 4 ints for k
    types += [float] * 48  # 48 floats for x
    pyccel_test(
        "scripts/return_numpy_arrays.py",
        language=language,
        output_dtype=types,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_array_binary_op(language, tmp_path):
    types = [int] * 4
    types += [int, float, int, int]
    types += [int] * 4
    types += [int, float, int, int]
    types += [int] * 4
    types += [int, float, int, int]
    types += [int] * 4
    types += [int, float, int, int]
    types += [int] * 8
    pyccel_test(
        "scripts/array_binary_operation.py",
        language=language,
        output_dtype=types,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/classes/classes.py",
        "scripts/classes/classes_1.py",
        "scripts/classes/classes_2.py",
        "scripts/classes/classes_3.py",
        "scripts/classes/classes_4.py",
        "scripts/classes/classes_5.py",
        "scripts/classes/classes_6.py",
        "scripts/classes/classes_7.py",
        "scripts/classes/classes_8.py",
        "scripts/classes/classes_9.py",
        "scripts/classes/pep526.py",
        "scripts/classes/class_variables.py",
        "scripts/classes/class_temporary_in_constructor.py",
        "scripts/classes/class_with_non_target_array_arg.py",
        "scripts/classes/class_pointer.py",
        "scripts/classes/class_pointer_2.py",
    ],
)
def test_classes(test_file, language, tmp_path):
    pyccel_test(test_file, language=language, isolated_dir=tmp_path)


def test_class_magic(language, tmp_path):
    pyccel_test(
        "scripts/classes/class_magic.py",
        language=language,
        output_dtype=[int] * 6 + [bool] * 2 + [int],
        isolated_dir=tmp_path,
    )


def test_tuples_in_classes(language, tmp_path):
    test_file = "scripts/classes/tuples_in_classes.py"
    pyccel_test(
        test_file,
        language=language,
        output_dtype=[float, float, float, bool, bool],
        isolated_dir=tmp_path,
    )


def test_classes_type_print(language):
    rel_test_dir = Path("scripts/classes")

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path(rel_test_dir))
    test_file = copy_to_isolated_dir(
        isolated_dir, rel_test_dir, "scripts/classes/empty_class.py"
    )
    cwd = isolated_dir

    pyccel_commands = " --language=" + language

    if language == "python":
        output_dir = isolated_dir / "__pyccel__"
        pyccel_commands += " --output " + str(output_dir)
        output_test_file = output_dir / test_file.name
    else:
        output_test_file = test_file

    compile_pyccel(cwd, test_file, pyccel_commands)

    lang_out = get_lang_output(output_test_file, language)

    rx = re.compile(r"\bA\b")
    assert rx.search(lang_out)


def test_class_inline_array(language, tmp_path):
    pyccel_test(
        "scripts/classes/class_inline.py",
        dependencies=["scripts/classes/importable.py"],
        language=language,
        output_dtype=float,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/classes/generic_methods.py",
    ],
)
def test_interfaces_in_classes(test_file, language, tmp_path):
    pyccel_test(test_file, language=language, isolated_dir=tmp_path)


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/lapack_subroutine.py",
    ],
)
@pytest.mark.skipif(
    sys.platform == "win32",
    reason="Compilation problem. On execution Windows raises: error while loading shared libraries: liblapack.dll: cannot open shared object file: No such file or directory",
)
@pytest.mark.external
@pytest.mark.fortran
def test_lapack(test_file):
    # TODO: Uncomment this when dgetri can be expressed with scipy
    # pyccel_test(test_file)

    # TODO: Remove the rest of the function when dgetri can be expressed with scipy
    test_file = get_abs_path(test_file)

    cwd = get_abs_path(".")

    compile_pyccel(cwd, test_file)

    lang_out = get_lang_output(test_file, "fortran")
    rx = re.compile("[-0-9.eE]+")
    lang_out_vals = []
    while lang_out:
        try:
            f, lang_out = get_value(lang_out, rx, float)
            lang_out_vals.append(f)
        except AssertionError:
            lang_out = None
    output_mat = np.array(lang_out_vals).reshape(4, 4)
    expected_output = np.eye(4)

    assert np.allclose(output_mat, expected_output, rtol=1e-14, atol=1e-15)


# ------------------------------------------------------------------------------
def test_type_print(experimental_language, tmp_path):
    pyccel_test(
        "scripts/runtest_type_print.py",
        language=experimental_language,
        output_dtype=str,
        isolated_dir=tmp_path,
    )


def test_container_type_print(language):
    rel_test_dir = Path("scripts")

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path(rel_test_dir))
    test_file = copy_to_isolated_dir(
        isolated_dir, rel_test_dir, "scripts/runtest_array_type_print.py"
    )
    cwd = isolated_dir

    pyccel_commands = " --language=" + language

    if language == "python":
        output_dir = isolated_dir / "__pyccel__"
        pyccel_commands += " --output " + str(output_dir)
        output_test_file = output_dir / test_file.name
    else:
        output_test_file = test_file

    compile_pyccel(cwd, test_file, pyccel_commands)

    lang_out = get_lang_output(output_test_file, language)

    rx = re.compile(r"\bnumpy.ndarray\b")
    assert rx.search(lang_out)

    if language != "python":
        rx = re.compile(r"\bfloat64\b")
        assert rx.search(lang_out)


# ------------------------------------------------------------------------------


def test_module_init(language):
    pyth_out = get_python_output(get_abs_path("scripts/runtest_module_init.py"))

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts"))
    test_mod = copy_to_isolated_dir(isolated_dir, "scripts", "scripts/module_init.py")
    test_prog = copy_to_isolated_dir(
        isolated_dir, "scripts", "scripts/runtest_module_init.py"
    )

    output_dir = isolated_dir / "__pyccel__"
    output_test_file = output_dir / test_prog.name

    cwd = isolated_dir

    pyccel_commands = "--language=" + language

    compile_pyccel(cwd, test_mod, pyccel_commands)

    if language != "python":
        pyth_mod_out = get_python_output(test_prog, cwd)
        compare_pyth_fort_output(pyth_out, pyth_mod_out, str, language)

    compile_pyccel(cwd, test_prog, pyccel_commands)

    if language == "python":
        lang_out = get_lang_output(output_test_file, language)
    else:
        lang_out = get_lang_output(test_prog, language)

    compare_pyth_fort_output(pyth_out, lang_out, str, language)


# ------------------------------------------------------------------------------
def get_lang_exit_value(abs_path, language, cwd=None):
    abs_path = get_exe(abs_path, language)
    if language == "python":
        if cwd is None:
            p = subprocess.run([sys.executable, abs_path], check=False)
        else:
            p = subprocess.run([sys.executable, abs_path], cwd=cwd, check=False)
    else:
        p = subprocess.run([abs_path], check=False)
    return p.returncode


@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/asserts/valid_assert.py",
        "scripts/asserts/invalid_assert1.py",
        "scripts/asserts/invalid_assert2.py",
        "scripts/asserts/invalid_assert3.py",
    ],
)
def test_assert(language, test_file):
    test_dir = Path(test_file).parent
    pyth_out = get_lang_exit_value(get_abs_path(test_file), "python")

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path(test_dir))
    test_file = copy_to_isolated_dir(isolated_dir, test_dir, test_file)

    output_dir = isolated_dir / "__pyccel__"
    output_test_file = output_dir / test_file.name

    cwd = isolated_dir

    pyccel_commands = " --language=" + language
    pyccel_commands += " --output=" + str(output_dir)
    pyccel_commands += " --debug"

    compile_pyccel(cwd, test_file, pyccel_commands)
    lang_out = get_lang_exit_value(output_test_file, language)
    assert (not lang_out and not pyth_out) or (lang_out and pyth_out)


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "test_file",
    [
        "scripts/exits/empty_exit.py",
        "scripts/exits/negative_exit1.py",
        "scripts/exits/negative_exit2.py",
        "scripts/exits/positive_exit1.py",
        "scripts/exits/positive_exit2.py",
        "scripts/exits/positive_exit3.py",
        "scripts/exits/zero_exit.py",
        "scripts/exits/error_message_exit.py",
    ],
)
def test_exit(language, test_file):
    test_dir = Path(test_file).parent
    pyth_out = get_lang_exit_value(get_abs_path(test_file), "python")

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path(test_dir))
    test_file = copy_to_isolated_dir(isolated_dir, test_dir, test_file)

    output_dir = isolated_dir / "__pyccel__"
    output_test_file = output_dir / test_file.name

    cwd = isolated_dir

    if not language:
        language = "fortran"
    pyccel_commands = " --language=" + language
    pyccel_commands += " --output=" + str(output_dir)

    compile_pyccel(cwd, test_file, pyccel_commands)
    lang_out = get_lang_exit_value(output_test_file, language)
    assert lang_out == pyth_out


# ------------------------------------------------------------------------------
def test_module_init_collisions(language):
    pyth_out = get_python_output(get_abs_path("scripts/runtest_module_init2.py"))

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts"))
    test_mod = copy_to_isolated_dir(isolated_dir, "scripts", "scripts/module_init2.py")
    test_prog = copy_to_isolated_dir(
        isolated_dir, "scripts", "scripts/runtest_module_init2.py"
    )

    output_dir = isolated_dir / "__pyccel__"
    output_test_file = output_dir / test_prog.name

    cwd = isolated_dir

    pyccel_commands = "--language=" + language

    compile_pyccel(cwd, test_mod, pyccel_commands)
    compile_pyccel(cwd, test_prog, pyccel_commands)

    if language == "python":
        lang_out = get_lang_output(output_test_file, language)
    else:
        lang_out = get_lang_output(test_prog, language)

    compare_pyth_fort_output(
        pyth_out,
        lang_out,
        [float, float, float, int, float, float, float, int],
        language,
    )


@pytest.mark.fortran
def test_function_aliasing(tmp_path):
    pyccel_test(
        "scripts/runtest_function_alias.py", language="fortran", isolated_dir=tmp_path
    )


# ------------------------------------------------------------------------------


def test_function(language, tmp_path):
    pyccel_test(
        "scripts/functions.py",
        language=language,
        output_dtype=str,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.skipif_by_language(
    os.environ.get("PYCCEL_DEFAULT_COMPILER", None) == "intel",
    reason="1671",
    language="fortran",
)
def test_inline(language, tmp_path):
    pyccel_test(
        "scripts/decorators_inline.py", language=language, isolated_dir=tmp_path
    )


# ------------------------------------------------------------------------------
@pytest.mark.skipif_by_language(
    os.environ.get("PYCCEL_DEFAULT_COMPILER", None) == "intel",
    reason="1671",
    language="fortran",
)
def test_inline_import(language, tmp_path):
    pyccel_test(
        "scripts/runtest_decorators_inline.py",
        dependencies=("scripts/decorators_inline.py"),
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.language_agnostic
def test_json():
    output_dir = get_abs_path(insert_pyccel_folder("scripts/"))
    cmd = [
        shutil.which("pyccel"),
        "config",
        "export",
        f"{output_dir}/test.json",
        "--compiler-family",
        "intel",
    ]
    subprocess.run(cmd, check=True)
    with open(get_abs_path(f"{output_dir}/test.json"), "r", encoding="utf-8") as f:
        dict_1 = json.load(f)
    assert dict_1["c"]["exec"] == "icx"
    cmd = [
        shutil.which("pyccel"),
        "config",
        "export",
        f"{output_dir}/test2.json",
        "--compiler-config",
        f"{output_dir}/test.json",
    ]
    subprocess.run(cmd, check=True)
    with open(get_abs_path(f"{output_dir}/test2.json"), "r", encoding="utf-8") as f:
        dict_2 = json.load(f)

    assert dict_1 == dict_2


@pytest.mark.language_agnostic
def test_json_relative_path():
    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts"))
    copy_to_isolated_dir(isolated_dir, "scripts", "scripts/runtest_funcs.py")

    cmd = [shutil.which("pyccel"), "config", "export", f"{isolated_dir}/test.json"]
    subprocess.run(cmd, check=True)

    hope_dir = isolated_dir / "hope_benchmarks"
    hope_dir.mkdir(parents=True, exist_ok=True)
    shutil.move(isolated_dir / "test.json", hope_dir / "test.json")
    compile_pyccel(
        hope_dir,
        "../runtest_funcs.py",
        "--compiler-config test.json",
    )


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "language",
    (
        pytest.param("fortran", marks=pytest.mark.fortran),
        pytest.param("c", marks=pytest.mark.c),
    ),
)
def test_json_register(language):
    output_dir = get_abs_path(insert_pyccel_folder("scripts/"))
    example_json_path = f"{output_dir}/test.json"
    cmd = [shutil.which("pyccel"), "config", "export", example_json_path]
    subprocess.run(cmd, check=True)
    with open(example_json_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    config[language]["debug_flags"] = "-g -O0"

    bad_format_json_path = f"{output_dir}/bad_format.json"
    with open(bad_format_json_path, "w", encoding="utf-8") as f:
        json.dump(config, f)

    # Check `pyccel config check` command
    cmd = [shutil.which("pyccel"), "config", "check", bad_format_json_path]
    p = subprocess.run(cmd, check=False)
    assert p.returncode == 1

    config[language]["debug_flags"] = ["-g", "-O0"]
    config[language]["general_flags"] = ["--version"]

    current_config_folder = os.environ.get("PYCCEL_CONFIG_HOME", None)
    os.environ["PYCCEL_CONFIG_HOME"] = str(get_abs_path(insert_pyccel_folder(".")))

    # Check registration
    timing_json_path = f"{output_dir}/timing.json"
    print(timing_json_path)
    with open(timing_json_path, "w", encoding="utf-8") as f:
        json.dump(config, f)
    cmd = [
        shutil.which("pyccel"),
        "config",
        "register",
        "compiler_timing",
        timing_json_path,
    ]
    subprocess.run(cmd, check=True)

    # Check that existing compiler-family can't be overwritten
    cmd = [
        shutil.which("pyccel"),
        "config",
        "register",
        "compiler_timing",
        example_json_path,
    ]
    p = subprocess.run(cmd, check=False)
    assert p.returncode == 1

    cmd = [
        shutil.which("pyccel"),
        "compile",
        "--compiler-family=compiler_timing",
        f"--language={language}",
        "-v",
        get_abs_path("scripts/array_binary_operation.py"),
    ]
    p = subprocess.run(cmd, check=True, text=True, capture_output=True)
    received_output = p.stdout

    # Check version output for selected compiler
    cmd = [shutil.which(config[language]["exec"]), "--version"]
    p = subprocess.run(cmd, check=True, text=True, capture_output=True)
    expected_output = p.stdout

    # Check version output is present to ensure new config is being used
    assert expected_output in received_output

    cmd = [shutil.which("pyccel"), "config", "remove", "compiler_timing"]
    subprocess.run(cmd, check=True)

    if current_config_folder:
        os.environ["PYCCEL_CONFIG_HOME"] = current_config_folder
    else:
        os.environ.pop("PYCCEL_CONFIG_HOME")


# ------------------------------------------------------------------------------
@pytest.mark.language_agnostic
def test_reserved_file_name():
    plugin_manager = pluggy.PluginManager("pyccel")

    with pytest.raises(ValueError) as exc_info:
        libname = str(random.choice(tuple(python_builtin_libs))) + ".py"  # nosec B311
        execute_pyccel(fname=libname, plugin_manager=plugin_manager)
    assert (
        str(exc_info.value)
        == f"File called {libname} has the same name as a Python built-in package and can't be imported from Python. See #1402"
    )


# ------------------------------------------------------------------------------
@pytest.mark.skip(reason="List concatenation not yet implemented")
def test_concatenation(language, tmp_path):
    pyccel_test(
        "scripts/concatenation.py",
        language=language,
        output_dtype=[int] * 15 + [str],
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.parametrize(
    "language",
    (
        pytest.param("fortran", marks=pytest.mark.fortran),
        pytest.param("c", marks=pytest.mark.c),
    ),
)
def test_class_imports(language):
    pyth_out = get_python_output(
        get_abs_path("project_class_imports/runtest.py"),
        get_abs_path("project_class_imports"),
    )

    isolated_dir = get_thread_local_subdir(
        dirname=get_abs_path("project_class_imports")
    )
    rel_test_dir = Path("project_class_imports")
    cwd = isolated_dir

    # runtest.py unconditionally imports all three modules, so every source
    # file must already be present (even before it is individually
    # pyccelized) for any of the checks below to run.
    test_file = copy_to_isolated_dir(
        isolated_dir, rel_test_dir, "project_class_imports/runtest.py"
    )
    point_mod = copy_to_isolated_dir(
        isolated_dir, rel_test_dir, "project_class_imports/project/basics/Point_mod.py"
    )
    line_mod = copy_to_isolated_dir(
        isolated_dir, rel_test_dir, "project_class_imports/project/basics/Line_mod.py"
    )
    square_mod = copy_to_isolated_dir(
        isolated_dir, rel_test_dir, "project_class_imports/project/shapes/Square_mod.py"
    )

    compile_pyccel(cwd, point_mod, f"--language={language} --verbose")

    out1 = get_python_output(test_file, cwd)
    compare_pyth_fort_output(pyth_out, out1, float, "python")

    compile_pyccel(cwd, line_mod, f"--language={language} --verbose")

    out2 = get_python_output(test_file, cwd)
    compare_pyth_fort_output(pyth_out, out2, float, "python")

    compile_pyccel(cwd, square_mod, f"--language={language} --verbose")

    out3 = get_python_output(test_file, cwd)
    compare_pyth_fort_output(pyth_out, out3, float, "python")

    compile_pyccel(cwd, test_file, f"--language={language} --verbose")

    lang_out = get_lang_output(test_file, language)
    compare_pyth_fort_output(pyth_out, lang_out, float, language)


# ------------------------------------------------------------------------------
def test_time_execution_flag(language):
    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts"))
    test_file = copy_to_isolated_dir(
        isolated_dir, "scripts", "scripts/runtest_funcs.py"
    )

    cwd = isolated_dir

    cmd = [
        shutil.which("pyccel"),
        "compile",
        test_file,
        f"--language={language}",
        "--time-execution",
    ]
    if language == "python":
        cmd.append(f"--output={isolated_dir / '__pyccel__'}")
    with subprocess.Popen(
        cmd,
        universal_newlines=True,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    ) as p:
        result, _ = p.communicate()

    result_lines = result.split("\n")
    assert "Timers" in result_lines[0]
    assert "Total" in result_lines[-2]
    for l in result_lines[1:-1]:
        assert " : " in l


# ------------------------------------------------------------------------------
def test_module_name_containing_conflict(language):
    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts"))
    endif_file = copy_to_isolated_dir(isolated_dir, "scripts", "scripts/endif.py")
    test_file = copy_to_isolated_dir(
        isolated_dir, "scripts", "scripts/runtest_badly_named_module.py"
    )
    compile_pyccel(isolated_dir, endif_file, options=f"--language={language}")

    out1 = get_python_output(test_file)
    out2 = get_python_output(test_file)

    assert out1 == out2


# ------------------------------------------------------------------------------
@pytest.mark.skipif(
    sys.platform == "win32" and not np.__version__.startswith("2."),
    reason="Integer mismatch with numpy 1.*",
)
def test_stubs(language):
    """
    This tests that a stub file is generated and ensures the stub files are
    still generated with the expected format. However it is not a good test.
    It prevents any changes being made to the output format and doesn't
    check that it can be parsed. This test should be replaced once stub files
    can be read.
    """
    with open(
        get_abs_path(f"scripts/runtest_stub.{language}.pyi"), "r", encoding="utf-8"
    ) as f:
        expected_pyi = f.read()

    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts"))
    test_file = copy_to_isolated_dir(isolated_dir, "scripts", "scripts/runtest_stub.py")

    wk_dir = isolated_dir / "stub_test"
    with FileLock(f"{wk_dir}.lock"):
        compile_pyccel(
            isolated_dir,
            test_file,
            options=f"--language={language} --output=stub_test",
        )
        with open(
            get_thread_local_subdir(dirname=wk_dir) / "runtest_stub.pyi",
            "r",
            encoding="utf-8",
        ) as f:
            generated_pyi = f.read()
        shutil.rmtree(wk_dir)

    assert expected_pyi == generated_pyi


# ------------------------------------------------------------------------------
def test_builtin_container_print(language, tmp_path):
    pyccel_test(
        "scripts/print_builtin_containers.py",
        output_dtype=str,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_pyccel_generated_compilation_dependency(language, tmp_path):
    pyccel_test(
        "scripts/runtest_pyccel_generated_compilation_dependency.py",
        dependencies=["scripts/pyccel_generated_compilation_dependency.py"],
        output_dtype=int,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_generated_name_collision(language, tmp_path):
    pyccel_test(
        "scripts/GENERATED_NAME_COLLISION.py",
        output_dtype=int,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_array_tuple_shape(language, tmp_path):
    pyccel_test(
        "scripts/array_tuple_shape.py",
        output_dtype=int,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_varargs(language, tmp_path):
    pyccel_test("scripts/runtest_varargs.py", language=language, isolated_dir=tmp_path)


# ------------------------------------------------------------------------------
@pytest.mark.python
def test_varkwargs(tmp_path):
    pyccel_test(
        "scripts/runtest_varkwargs.py",
        language="python",
        output_dtype=str,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.skipif_by_language(
    os.environ.get("PYCCEL_DEFAULT_COMPILER", None) == "intel",
    reason="1671",
    language="fortran",
)
def test_inline_using_import(language, tmp_path):
    test_file = Path("scripts/inlining/runtest_inline_using_import.py")
    pyccel_test(
        test_file,
        dependencies=[
            "scripts/inlining/my_func.py",
            "scripts/inlining/my_other_func.py",
            "scripts/inlining/inline_using_import.py",
        ],
        language=language,
        output_dtype=float,
        isolated_dir=tmp_path,
    )

    if language != "python":
        test_abspath = tmp_path / test_file.name

        cwd = test_abspath.parent
        pyth_out = get_python_output(test_abspath, cwd)
        lang_out = get_lang_output(get_exe(test_abspath, language), language)
        compare_pyth_fort_output(pyth_out, lang_out, float, language)


# ------------------------------------------------------------------------------
@pytest.mark.skipif_by_language(
    os.environ.get("PYCCEL_DEFAULT_COMPILER", None) == "intel",
    reason="1671",
    language="fortran",
)
def test_inline_using_import_2(language, tmp_path):
    pyccel_test(
        "scripts/inlining/runtest_inline_using_import_2.py",
        dependencies=[
            "scripts/inlining/my_func.py",
            "scripts/inlining/my_other_func.py",
            "scripts/inlining/inline_using_import.py",
        ],
        language=language,
        output_dtype=float,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
@pytest.mark.skipif_by_language(
    os.environ.get("PYCCEL_DEFAULT_COMPILER", None) == "intel",
    reason="1671",
    language="fortran",
)
def test_inline_using_named_import(language, tmp_path):
    pyccel_test(
        "scripts/inlining/runtest_inline_using_named_import.py",
        dependencies=[
            "scripts/inlining/my_func.py",
            "scripts/inlining/my_func2.py",
            "scripts/inlining/inline_using_named_import.py",
        ],
        language=language,
        output_dtype=float,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_classes_array_property(language, tmp_path):
    pyccel_test(
        "scripts/classes/runtest_classes_array_property.py",
        dependencies=["scripts/classes/classes_array_property.py"],
        language=language,
        output_dtype=float,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_classes_pointer_import(language):
    cwd = get_abs_path("scripts/classes")
    test_file = get_abs_path("scripts/classes/runtest_class_pointer_2.py")

    pyth_out = get_python_output(test_file, cwd)

    dependency = get_abs_path("scripts/classes/class_pointer_2.py")
    compile_pyccel(cwd, dependency, f"--language={language}")

    pyth_interface_out = get_python_output(test_file, cwd)
    assert pyth_out == pyth_interface_out

    compile_pyccel(cwd, test_file, f"--language={language}")

    lang_out = get_lang_output(test_file, language)
    compare_pyth_fort_output(pyth_out, lang_out, float, language)


# ------------------------------------------------------------------------------
def test_functional_statements(language, tmp_path):
    pyccel_test(
        "scripts/functional_statements.py",
        output_dtype=[int] * 9,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_complex_numbers(language, tmp_path):
    pyccel_test(
        "scripts/complex_numbers.py",
        output_dtype=[complex] * 6,
        language=language,
        isolated_dir=tmp_path,
    )


# ------------------------------------------------------------------------------
def test_line_annotation_plugin(language):
    isolated_dir = get_thread_local_subdir(dirname=get_abs_path("scripts"))
    test_file = copy_to_isolated_dir(isolated_dir, "scripts", "scripts/funcs.py")
    folder = test_file.parent

    # Choose an output folder that cannot contain translations of other files
    output_folder = folder / "__pyccel__la__"

    pyccel_commands = (
        "-t --line_annotation --language=" + language + f" --output={output_folder}"
    )

    shutil.rmtree(output_folder, ignore_errors=True)

    compile_pyccel(folder, test_file, pyccel_commands)

    for fi in output_folder.iterdir():
        if fi.suffix in (".c", ".f90", ".py"):
            with open(fi, "r", encoding="utf-8") as file:
                code = file.read()
            assert str(test_file) in code
