# coding: utf-8
#------------------------------------------------------------------------------------------#
# This file is part of Pyccel which is released under MIT License. See the LICENSE file or #
# go to https://github.com/pyccel/pyccel/blob/devel/LICENSE for full license details.      #
#------------------------------------------------------------------------------------------#
""" Module containing scripts to remove pyccel generated objects
"""
import os
import shutil
import sysconfig
from argparse import ArgumentParser

ext_suffix = sysconfig.get_config_var('EXT_SUFFIX')


def remove_pyccel_folders(file_name):
    """Remove __pyccel__ or __epyccel__ folders"""
    if os.path.basename(file_name).startswith(("__pyccel__", "__epyccel__")):
        shutil.rmtree(file_name, ignore_errors=True)
        return True
    return False


def remove_pyccel_files(file_name, remove_shared_libs=False, remove_programs=False):
    """Remove files generated by Pyccel based on type and flags"""
    if file_name.endswith('.pyccel'):
        os.remove(file_name)
        return True
    if remove_shared_libs and file_name.endswith(ext_suffix):
        os.remove(file_name)
        return True
    if remove_programs and os.access(file_name, os.X_OK):
        os.remove(file_name)
        return True
    return False


def pyccel_clean(path_dir=None, recursive=True, remove_shared_libs=False, remove_programs=False):
    """
    Remove folders and files generated by Pyccel.

    Parameters
    ----------
    path_dir : str, default = current working directory
        The path to the folder which should be cleaned.

    recursive : bool, default = True
        Indicates whether the function should recurse into sub-folders.

    remove_shared_libs : bool, default = False
        Indicates whether Python shared libraries should be removed.

    remove_programs : bool, default = False
        Indicates whether programs should be removed.
    """
    if path_dir is None:
        path_dir = os.getcwd()

    files = os.listdir(path_dir)
    for f in files:
        file_name = os.path.join(path_dir, f)

        if remove_pyccel_folders(file_name):
            continue
        elif not os.path.isfile(file_name) and recursive:
            pyccel_clean(file_name, recursive, remove_shared_libs, remove_programs)
            if not os.listdir(file_name):
                os.rmdir(file_name)
        elif remove_pyccel_files(file_name, remove_shared_libs, remove_programs):
            continue


def pyccel_clean_command():
    """
    Command line wrapper around the pyccel_clean function.
    """
    parser = ArgumentParser(description='Tool for removing files generated by pyccel')

    parser.add_argument('folders', metavar='N', type=str, nargs='*',
                        help='The folders to be cleaned (default is the current folder)')
    parser.add_argument('-n', '--not-recursive', action='store_false',
                        help='Only run pyccel-clean in the current directory. Do not recurse into other folders')
    parser.add_argument('-s', '--remove-libs', action='store_true',
                        help='Also remove any libraries generated by Python from the folder. Beware this may remove shared libraries generated by tools other than pyccel')
    parser.add_argument('-p', '--remove-programs', action='store_true',
                        help='Also remove any programs from the folder. Beware this may remove programs unrelated to pyccel')
    args = parser.parse_args()

    folders = args.folders
    recursive = args.not_recursive
    remove_libs = args.remove_libs
    remove_programs = args.remove_programs

    if not folders:
        pyccel_clean(None, recursive, remove_libs, remove_programs)
    else:
        for f in folders:
            pyccel_clean(f, recursive, remove_libs, remove_programs)
