# coding: utf-8
#------------------------------------------------------------------------------------------#
# This file is part of Pyccel which is released under MIT License. See the LICENSE file or #
# go to https://github.com/pyccel/pyccel/blob/devel/LICENSE for full license details.      #
#------------------------------------------------------------------------------------------#
""" Module containing scripts to run the unit tests of Pyccel
"""
import os
import subprocess
from argparse import ArgumentParser


def pyccel_test():
    """
    Run the unit tests of Pyccel.

    This function runs the unit tests of Pyccel using pytest.
    It first checks if pytest is installed, and if not, it
    installs it using pip. Then, it runs the tests using
    pytest and generates a coverage report. The function
    also checks if the tests are run in a virtual environment,
    and if so, it generates a coverage report for the virtual
    environment. Finally, it cleans up the temporary files
    generated during the test run.

    """

    try:
        import pytest
    except ImportError:
        print("pytest is not installed. Installing pytest...")
        os.system('pip install pytest')
        import pytest

#    try:
#        import coverage
#    except ImportError:
#        print("coverage is not installed. Installing coverage...")
#        os.system('pip install coverage')
#        import coverage
#
#    try:
#        import pytest_cov
#    except ImportError:
#        print("pytest_cov is not installed. Installing pytest_cov...")
#        os.system('pip install pytest_cov')
#        import pytest_cov

    try:
        import xdist
    except ImportError:
        print("pytest-xdist is not installed. Installing pytest_xdist...")
        os.system('pip install pytest-xdist')
        import xdist

#    subprocess.run(['curl', '-JLO', 'https://github.com/pyccel/pyccel/archive/refs/heads/devel.zip'])
#    subprocess.run(['unzip', '-o', 'pyccel-devel.zip'])

    # Download our dependencies if needed with `pip install "pyccel[test]"`

    # Determine the version of Pyccel that we are using

    # Download the test files
    from urllib.request import urlretrieve
    print("Downloading the test files from GitHub...")
    filepath = urlretrieve('https://github.com/pyccel/pyccel/archive/refs/heads/devel.zip', filename='pyccel.zip')

    # Unzip the test files
    import zipfile
    print("Unzipping the test files...")
    with zipfile.ZipFile('pyccel.zip', 'r') as archive:
        for file in archive.namelist():
            if file.startswith('pyccel-devel/tests'):
                archive.extract(file, path='.')

    # Change into the test directory
    print("Changing into the test directory...")
    os.chdir('pyccel-devel/tests')

    print("Run the single-process tests which must be run one at a time")
    retcode = pytest.main(['-ra', '-m (not parallel and xdist_incompatible)'])

    print("Run the single-process tests which can be run in parallel")
    retcode = pytest.main(['-ra', '-m (not parallel and not xdist_incompatible)', '-n', 'auto'])

#    return retcode


def pyccel_test_command():
    """
    Command line wrapper around the pyccel_test function.

    A wrapper around the pyccel_test function which allows
    command line arguments to be passed to the function.
    """
    parser = ArgumentParser(description='Tool for running the test suite of Pyccel')


#    parser.add_argument('folders', metavar='N', type=str, nargs='*',
#            help='The folders to be cleaned (default is the current folder')
#    parser.add_argument('-n', '--not-recursive', action='store_false',
#            help='Only run pyccel-clean in the current directory. Do not recurse into other folders')
#    parser.add_argument('-s', '--remove-libs', action='store_true',
#            help='Also remove any libraries generated by Python from the folder. Beware this may remove shared libraries generated by tools other than pyccel')

    args = parser.parse_args()

    pyccel_test()


if __name__ == "__main__":
    pyccel_test_command()
