SET(LAPACK_DIR    "${BLASLAPACK_DIR}")
SET(LAPACK_INCLUDE "${LAPACK_DIR}")
SET(LAPACK_LIB_DIR "${LAPACK_DIR}")

FIND_LIBRARY(BLAS_LIB NAMES libblas.a
             HINTS ${LAPACK_LIB_DIR})

FIND_LIBRARY(LAPACK_LIB NAMES liblapack.a
             HINTS ${LAPACK_LIB_DIR})

SET(BLAS_LIBRARIES ${BLAS_LIB})
SET(LAPACK_LIBRARIES ${LAPACK_LIB} ${BLAS_LIB})
SET(LAPACK_INCLUDES ${LAPACK_INCLUDE})
  
SET (LAPACK_INCLUDES  ${LAPACK_INCLUDES}  CACHE STRING "LAPACK include path" FORCE)
SET (LAPACK_LIBRARIES ${LAPACK_LIBRARIES} CACHE STRING "LAPACK libraries"    FORCE)

MARK_AS_ADVANCED(LAPACK_INCLUDES LAPACK_LIBRARIES)

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args (LAPACK "LAPACK could not be found.  Be sure to set BLASLAPACK_DIR." LAPACK_INCLUDES LAPACK_LIBRARIES)

IF (LAPACK_FOUND)
  INCLUDE_DIRECTORIES(${LAPACK_INCLUDES})
  MESSAGE(STATUS "LAPACK Has been found using BLASLAPACK_DIR")
  MESSAGE(STATUS "LAPACK_DIR: ${LAPACK_DIR}")
  MESSAGE(STATUS "LAPACK_INCLUDES: ${LAPACK_INCLUDES}")
  MESSAGE(STATUS "LAPACK_LIBRARIES: ${LAPACK_LIBRARIES}")
ENDIF(LAPACK_FOUND)
