name: "Generate bot token"
inputs:
  bot_pem:
    description: "The private key which identfies the bot"
    required: true
outputs:
  installation_token:
    description: "The token which will allow you to authentificate as the GitHub app for 1 hour"
    value: ${{ steps.get_token.outputs.token }}

runs:
  using: "composite"
  steps:
    - run: |
        pip install jwt requests
      shell: bash
    - run: |
        import jwt
        import time
        import os
        import requests
        signing_key = jwt.jwk_from_pem(bytes(os.environ["PEM"], "utf-8"))
        # Issued at time
        # JWT expiration time (10 minutes maximum)
        # GitHub App's identifier
        payload = {'iat': int(time.time()), 'exp': int(time.time()) + 60, 'iss': 337566}

        jw_token=jwt.JWT().encode(payload, signing_key, alg='RS256')

        headers = {"Accept": "application/vnd.github+json", "Authorization": f"Bearer {jw_token}", "X-GitHub-Api-Version": "2022-11-28"}

        reply = requests.post("https://api.github.com/app/installations/37820767/access_tokens", headers=headers)

        t = reply.json()["token"]

        # Create JWT
        with open("${{ github.output }}", 'a') as f:
            print("token=", t, sep='', file = f)
      shell: python
      id: get_token
      env:
        PEM: ${{ inputs.bot_pem }}
