name: 'Pyccel pytest commands generating python'
inputs:
  shell_cmd:
    description: 'Specifies the shell command (different for anaconda)'
    required: false
    default: "bash"

runs:
  using: "composite"
  steps:
    - name: Python tests with pytest
      run: |
        python -m pytest -n auto -rXx -m "not (parallel or xdist_incompatible) and python" --ignore=symbolic --ignore=ndarrays --ignore=cuda_ndarrays
        python -m pytest -rXx -m "xdist_incompatible and not parallel and python" --ignore=symbolic --ignore=ndarrays --ignore=cuda_ndarrays
        pyccel-clean
      shell: ${{ inputs.shell_cmd }}
      working-directory: ./tests
