name: 'Ensure gFTL is installed with Pyccel'
inputs:
  not_editable:
    description: 'not_editable installation'
    default: 'True'
runs:
  using: "composite"
  steps:
    - name: check gFTL installation
      shell: python
      run: |
        import pyccel
        from os.path import exists, join
        pyccel_loc = pyccel.__path__[0]
        print(pyccel_loc)
        assert exists(join(pyccel_loc,'extensions/gFTL/install/GFTL-1.13/include/v2'))
        if ${{ inputs.not_editable }}:
          assert not exists(join(pyccel_loc,'extensions/gFTL/doc'))

