name: 'Ensure gFTL is installed with Pyccel'
inputs:
  not_editable:
    description: 'not_editable installation'
    default: 'True'
runs:
  using: "composite"
  steps:
    - name: check gFTL installation
      shell: python
      run: |
        import importlib.resources
        extensions = importlib.resources.files(f'pyccel.extensions')
        gftl_folder = extensions.joinpath(f'gFTL-install')
        gftl_folder_gen = importlib.resources.as_file(gftl_folder)
        f = gftl_folder_gen.__enter__()
        assert f.exists()
        assert len(f.glob('**/*.cmake')) > 0
        assert len(f.glob('**/*.inc')) > 0
        f.__exit__()

