name: 'Ensure gFTL is installed with Pyccel'
inputs:
  not_editable:
    description: 'not_editable installation'
    default: 'True'
runs:
  using: "composite"
  steps:
    - name: check gFTL installation
      shell: python
      run: |
        import importlib.resources
        gftl_folder = importlib.resources.files(f'pyccel.extensions.gftl_install')
        with importlib.resources.as_file(gftl_folder) as f:
          assert f.exists()
          assert len(list(f.glob('**/*.cmake'))) > 0
          assert len(list(f.glob('**/*.inc'))) > 0

