name: 'Ensure STC is installed with Pyccel'
inputs:
  not_editable:
    description: 'not_editable installation'
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: check stc installation
      shell: python
      run: |
        import pyccel, os
        from os.path import exists, join
        pyccel_loc = pyccel.__path__[0]
        print(pyccel_loc)
        assert(exists(join(pyccel_loc,'extensions/STC/include/stc')))
        if ${{ inputs.not_editable }}:
          assert(not exists(join(pyccel_loc,'extensions/STC/docs')))
