name: 'Ensure STC is installed with Pyccel'

runs:
  using: "composite"
  steps:
    - name: check stc installation
      shell: python
      run: |
        import pyccel, os
        from os.path import exists, join
        pyccel_loc = pyccel.__path__[0]
        input = os.getenv('editable')
        print(pyccel_loc)
        assert(exists(join(pyccel_loc,'extensions/STC/include/stc')))
        if input is not None:
          assert(not exists(join(pyccel_loc,'extensions/STC/docs')))
