name: 'Ensure STC is installed with Pyccel'
inputs:
  not_editable:
    description: 'not_editable installation'
    default: 'True'
runs:
  using: "composite"
  steps:
    - name: check stc installation
      shell: python
      run: |
        import importlib.resources
        stc_folder = importlib.resources.files(f'pyccel.extensions.stc_install_GNU')
        stc_folder_gen = importlib.resources.as_file(stc_folder)
        f = stc_folder_gen.__enter__()
        assert f.exists()
        assert len(list(f.glob('**/*.h'))) > 0
        assert len(list(f.glob('**/*.pc'))) > 0
        f.__exit__()

