name: 'Ensure STC is installed with Pyccel'

runs:
  using: "composite"
  steps:
    - name: check stc installation
      shell: python
      run: |
        import pyccel, os
        from os.path import exists, join
        pyccel_loc = pyccel.__path__[0]
        print(pyccel_loc)
        files = os.listdir(directory)
        for file in files:
          print("---> ",file)
        assert(exists(join(pyccel_loc,'stc')))
