name: 'Ensure STC is installed with Pyccel'

runs:
  using: "composite"
  steps:
    - name: check stc installation
      shell: python
      run: |
        import pyccel, os
        from os.path import exists, join
        pyccel_loc = pyccel.__path__[0]
        print(pyccel_loc)
        assert(exists(join(pyccel_loc,'extensions/STC/include/stc')))
        if not os.access(pyccel_loc, os.W_OK):
          assert(not exists(join(pyccel_loc,'extensions/STC/docs')))
