name: 'Ensure STC is installed with Pyccel'

runs:
  using: "composite"
  steps:
    - name: check stc installation
      shell: python
      run: |
        import os
        base_dir = os.getcwd()
        print("-=-=-=-=>", base_dir)
        stc_check = 'pyccel/stc'
        files = os.listdir('.')
        for file in files:
            print(file)
        print("=-=-++_++=> ", stc_check)
        contents = os.listdir('extensions/STC')
        for item in contents:
            print("=-=-=-=-=====> ",item)
        path = os.path.join(base_dir, stc_check)        
        print(path)
        assert(os.path.exists(path))
