name: 'Pyccel valgrind script'

runs:
  using: "composite"
  steps:
    - name: Test with valgrind for memory leaks
      run: |
        pyccel --language=c --flags="-g -O0" leaks_check.py
        valgrind --leak-check=full --error-exitcode=1 ./prog_leaks_check
      shell: bash
      working-directory: ./tests/ndarrays