name: 'Pyccel valgrind script'

runs:
  using: "composite"
  steps:
    - name: Test with valgrind for memory leaks in ndarrays
      run: |
        pyccel --language=c --flags="-g -O0" leaks_check.py
        valgrind --leak-check=full --error-exitcode=1 ./leaks_check
      shell: bash
      working-directory: ./tests/ndarrays
    
    - name: Test with valgrind for memory leaks in built-in containers
      run: |
        pyccel --language=c --flags="-g -O0" leaks_check.py
        valgrind --leak-check=full --error-exitcode=1 ./leaks_check
        pyccel-clean -p
        pyccel --language=fortran --flags="-g -O0" leaks_check.py
        valgrind --leak-check=full --error-exitcode=1 ./leaks_check
        pyccel-clean -p
        pyccel --language=c --flags="-g -O0" nested_leaks_check.py
        valgrind --leak-check=full --error-exitcode=1 ./nested_leaks_check
      shell: bash
      working-directory: ./tests/stc_containers
