name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install open-mpi
        brew install libomp
        brew install gcc
      shell: bash
