name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install open-mpi
        brew install libomp
        ln -s gfortran-8 gfortran
        echo "MPI_OPTS='--oversubscribe'" >> $GITHUB_ENV
      shell: bash
