name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install open-mpi
        brew install libomp
        if [[ ! -f "/usr/local/bin/gfortran" ]]; then
          gfort=$(ls /usr/local/bin/gfortran-* | tail -n 1)
          ln -s ${gfort} /usr/local/bin/gfortran
        fi
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
      shell: bash
