name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install gfortran # Ensure gfortran is installed
        brew install open-mpi
        brew install libomp
        which gcc
        GFORTRAN_FILE=$(which gfortran)
        echo $GFORTRAN_FILE
        if [[ ! -f "$GFORTRAN_FILE" ]]; then
          ls /usr/local/bin/
          which gcc
          gfort=$(ls /usr/local/bin/gfortran-* | tail -n 1)
          ln -s ${gfort} /usr/local/bin/gfortran
        fi
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
      shell: bash
