name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install open-mpi
        brew install libomp
        GFORTRAN_HOME=$(which gfortran || true)
        echo "GFORTRAN_HOME : $GFORTRAN_HOME"
        if [[ ! -f "$GFORTRAN_HOME" ]]; then
          gfort=$(sudo find / -name gfortran-* | tail -n 1)
          echo "Found $gfort"
          ln -s ${gfort} /opt/homebrew/bin/gfortran
        fi
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
      shell: bash
