name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install open-mpi
        brew reinstall libomp
        if [[ ! -f "/usr/local/bin/gfortran" ]]; then
          ln -s /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
        fi
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
      shell: bash
