name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install open-mpi
        brew install libomp
        brew install gfortran
        #if [[ ! -f "/usr/local/bin/gfortran" ]]; then
        #  echo "No gfortran!"
        #  ln -s /usr/local/bin/gfortran-8 /usr/local/bin/gfortran
        #  ls /usr/local/bin/gfortran
        #else
        #  echo "Found gfortran!"
        #  ls /usr/local/bin/gfortran
        #fi
        echo "MPI_OPTS=--oversubscribe" >> $GITHUB_ENV
        echo "${PATH}"
      shell: bash
