name: 'Pyccel pip commands for testing'

runs:
  using: "composite"
  steps:
    - name: Install scipy
      shell: bash
      run:
        conda install -c anaconda scipy
    - name: Install mpi4py
      shell: bash
      run:
        conda install -c conda-forge mpi4py
    - name: Install tblib
      shell: bash
      run:
        conda install -c anaconda tblib
    - name: Install pytest
      shell: bash
      run:
        conda install -c anaconda pytest
    - name: Install parallel pytest
      shell: bash
      run:
        conda install -c conda-forge pytest-xdist
    - name: Install astunparse
      shell: bash
      run:
        conda install -c anaconda astunparse
    - name: Install pyccel
      shell: bash
      run:
        python -m pip install .
