name: Unit test coverage

on:
  workflow_run:
    workflows: ["PR Tests"]
    types: [completed]
  workflow_dispatch:
    inputs:
      python_version:
        required: false
        type: string
        default: '3.10'
      run_id:
        description: "The id of the run where the artifacts can be found, by default the last run automatically triggered on the PR"
        required: false
        type: string
        default: ''
      pr_repo:
        description: "The repository where the tests ran, by default the current repo."
        required: false
        type: string

permissions:
  actions: read
  pull-requests: write

env:
  PYTHON_VERSION: ${{ inputs.python_version || '3.10' }}

jobs:
  CoverageChecker:

    runs-on: ubuntu-latest
    name: Unit tests
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v6
        with:
          path: origin
      - name: Get PR info
        id: pr_info
        run: |
          cd origin # Run in origin so gh connects to target repo
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            HEAD_SHA="${{ github.sha }}"
            echo "head_sha=${HEAD_SHA}" >> $GITHUB_OUTPUT
            echo "pr_repo=${{ inputs.pr_repo || github.repository }}" >> $GITHUB_OUTPUT
            if [ -n "${{ inputs.run_id }}" ]
            then
              echo "run_id=${{ inputs.run_id }}" >> $GITHUB_OUTPUT
            else
              PR_NUMBER=$(gh pr list --state open --json number,headRefOid \
                          --jq '.[] | select(.headRefOid == "${{ github.event.workflow_run.head_sha }}") | .number')
              link=$(gh pr checks $PR_NUMBER --required --json=workflow,state,link \
                     --jq='.[] | select(.workflow == "PR Tests" and .workflow == "SUCCESS") | .link')
              run_id=$(echo "$link" | grep -oP '(?<=/runs/)[0-9]+')
              echo "run_id=${run_id}" >> $GITHUB_OUTPUT
            fi
          else
            HEAD_SHA="${{ github.event.workflow_run.head_sha }}"
            echo "head_sha=$HEAD_SHA" >> $GITHUB_OUTPUT
            echo "pr_repo=${{ github.event.workflow_run.head_repository.full_name }}" >> $GITHUB_OUTPUT
            echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          fi
          BASE_SHA=$(gh pr list --state open --json headRefOid,baseRefOid \
            --jq ".[] | select(.headRefOid == \"$HEAD_SHA\") | .baseRefOid")
          echo "base=$BASE_SHA" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v6
        with:
          ref: ${{ steps.pr_info.outputs.head_sha }}
          repository: ${{ steps.pr_info.outputs.pr_repo }}
          submodules: true
          fetch-depth: 0
          path: pr_contents
      - name: Fetch base from upstream
        if: steps.pr_info.outputs.pr_repo != github.repository
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream
        shell: bash
        working-directory: pr_contents
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install defusedxml
          python -m pip install coverage
        shell: bash
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.pr_info.outputs.run_id }}
          pattern: coverage-artifact*
          path: pr_contents/coverage_files
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Collect coverage information
        run: |
          echo -e "[paths]\nsource =\n   $(pwd)/pyccel\n   */site-packages/pyccel\n[xml]\noutput = cobertura.xml" > .coveragerc
          coverage combine $(find coverage_files -name '.coverage')
          coverage xml
        shell: bash
        working-directory: pr_contents
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        continue-on-error: True
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: pr_contents/cobertura.xml
      - name: Collect diff information
        run: |
          git diff ${{ steps.pr_info.outputs.base }}..HEAD --no-indent-heuristic --unified=0 --output=pull_diff.txt --no-color
        shell: bash
        working-directory: pr_contents
      - name: Check coverage
        id: coverage
        run: |
          python ci_tools/check_new_coverage.py pull_diff.txt cobertura.xml $GITHUB_STEP_SUMMARY
        shell: bash
        working-directory: pr_contents
