name: Bot

on:
  push:
    branches: [ devel ]

jobs:
  Bot:
    name: Launch tests
    runs-on: ubuntu-latest
    if: github.repository == 'pyccel/pyccel'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install python dependencies
        run: |
          python -m pip install requests
      - name: "Generate token"
        id: token
        uses: ./.github/actions/generate_bot_token
        with:
          bot_pem: "${{ secrets.BOT_PEM }}"
      - id: run_bot
        run: |
          python ci_tools/devel_branch_tests.py
        env:
          GH_TOKEN: ${{ github.token }}
