# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pyccel tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    python-version: [3.8]
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:

        - os: ubuntu-latest
          python-version: 3.5

        - os: ubuntu-latest
          python-version: 3.6
          if: branch = master

        - os: ubuntu-latest
          python-version: 3.7
          if: branch = master

        - os: ubuntu-latest
          python-version: 3.8
          if: branch = master

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install scipy
        python -m pip install mpi4py
        python -m pip install tblib
        python -m pip install "pytest>=4.5"
    - name: Test with pytest
      run: |
        cd tests
        python -m pytest -rx -m "not parallel and c" --ignore=ast --ignore=printers --ignore=symbolic --ignore=ndarrays
        python -m pytest -rx -m "not parallel and not c" --ignore=ast --ignore=printers --ignore=symbolic --ignore=ndarrays
        python -m pytest ndarrays/ -rx
        mpiexec -n 4 ${MPI_OPTS} python -m pytest epyccel/test_parallel_epyccel.py -v -m parallel -rx
#        mpiexec -n 4 ${MPI_OPTS} python -m pytest epyccel -v -m parallel -rx
        cd ..

