# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pyccel tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]

    steps:
      - uses: ./.github/actions/linux_tests

  Linux:

    runs-on: ubuntu-latest
    if: branch = master
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: ./.github/actions/linux_tests
