name: Markdown lint

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: '3.12'

env:
  PYTHON_VERSION: ${{ inputs.python_version }}

jobs:
  Markdown:
    name: Markdown format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Markdownlint
        id: md_test
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          config: './.markdownlint.json'
          globs: '**.md,!.github/*'
