name: 'Pyccel pip commands for testing'

runs:
  steps:
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install .
        python -m pip install scipy
        python -m pip install mpi4py
        python -m pip install tblib
        python -m pip install "pytest>=4.5"

