name: Update PR following unit tests

on:
  workflow_run:
    workflows: ["PR Tests", "Unit test coverage"]
    types: [completed]

permissions:
  pull-requests: write

jobs:
  update_status:
    name: Update PR status
    if: (github.event.workflow_run.name == 'PR Tests' && github.event.workflow_run.conclusion != 'success') || github.event.workflow_run.name == 'Unit test coverage'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Find PR number
        id: find_pr
        run: |
          PR_NUMBER=$(gh pr list --state open --json number,headRefOid \
            --jq '.[] | select(.headRefOid == "${{ github.event.workflow_run.head_sha }}") | .number')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Check status
        id: status_check
        run:
          status=$(gh pr checks ${PR_NUMBER} --required --json state --jq '.[]["state"]' | sort -u)
          if [[ $status == "SUCCESS" ]]
          then
            echo "conclusion=SUCCESS"
          elif [[ $status == *"FAILURE"* ]]
          then
            echo "conclusion=FAILURE"
          fi
      - name: Convert PR to draft
        if: steps.find_pr.outputs.pr_number != '' && github.status_check.conclusion == 'FAILURE'
        run: |
          gh pr ready ${{ steps.find_pr.outputs.pr_number }} --undo
          gh pr edit --remove-label needs_initial_review
          gh pr edit --remove-label Ready_for_review
          gh pr edit --remove-label Ready_to_merge
          gh pr comment ${{ steps.find_pr.outputs.pr_number }} --body "Unfortunately your PR is not passing the tests so it is not quite ready for review yet."
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Update label
        id: update_label
        if: steps.find_pr.outputs.pr_number != '' && github.status_check.conclusion == 'SUCCESS'
        uses: ./.github/actions/update_review_label
        with:
          pr_number: ${{ steps.find_pr.outputs.pr_number }}
      - name: Post comment
        if: steps.find_pr.outputs.pr_number != '' && github.status_check.conclusion == 'SUCCESS'
        run: |
          PR_NUMBER=${{ steps.find_pr.outputs.pr_number }}
          if [ -n "${{ steps.update_label.outputs.requesters }}" ]; then
            MESSAGE=$(sed "s/{reviewers}/${{ steps.update_label.outputs.requesters }}/g; s/{author}/${{ steps.update_label.outputs.author }}/g" \
              ci_tools/bot_messages/rerequest_review.txt)
            gh pr comment $PR_NUMBER --body "$MESSAGE"
          elif [ "${{ steps.update_label.outputs.label }}" = "needs_initial_review" ]; then
            MESSAGE=$(sed "s/{author}/${{ steps.update_label.outputs.author }}/g" ci_tools/bot_messages/new_pr.txt)
            gh pr comment $PR_NUMBER --body "$MESSAGE"
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
