name: PR Static Analysis

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pyccel_lint:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/pyccel_lint.yml
    secrets: inherit

  pylint:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/pylint.yml
    with:
      base: ${{ github.event.pull_request.base.sha }}
    secrets: inherit

  docs:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/docs.yml
    with:
      base: ${{ github.event.pull_request.base.sha }}
    secrets: inherit

  spelling:
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/spelling.yml
    secrets: inherit
