name: Python Linting

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: '3.10'
      base:
        required: false
        type: string

env:
  PYTHON_VERSION: ${{ inputs.python_version }}
  BASE: ${{ inputs.base || github.event.pull_request.base.sha }}

jobs:
  Linter:
    runs-on: ubuntu-latest
    name: Python best practices (pylint, ${{ inputs.python_version }})

    steps:
      - id: duplicate_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          skip_after_successful_duplicate: 'true'
          paths: '["**/*.py", ".github/workflows/pylint.yml", ".github/actions/**"]'
          do_not_skip: '["push"]'

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install python dependencies
        if: steps.duplicate_check.outputs.should_skip != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint
          python -m pip install defusedxml
        shell: bash
      - name: Run Pylint
        if: steps.duplicate_check.outputs.should_skip != 'true'
        run: |
          check_files=$(git diff ${{ env.BASE }}..HEAD --name-only --diff-filter=AM | grep "\.py$" || true)
          if [ -z ${check_files} ]
          then
            touch pylint_results.txt
          else
            python -m pylint --rcfile=.pylintrc ${check_files} 2>&1 | tee pylint_results.txt || true
          fi
        shell: bash
      - name: Filter Pylint output
        if: steps.duplicate_check.outputs.should_skip != 'true'
        id: pylint
        run: |
          git diff ${{ env.BASE }}..HEAD --no-indent-heuristic --unified=0 --output=pull_diff.txt --no-color
          python ci_tools/parse_pylint_output.py pylint_results.txt pull_diff.txt $GITHUB_STEP_SUMMARY
        shell: bash
