name: Bot

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  issues: write

jobs:
  Bot:
    name: Update Review Stage
    if: (! github.event.pull_request.draft) && github.event.review.user.type != 'Bot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set PR to draft on changes requested
        if: github.event.review.state == 'changes_requested'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          AUTHOR=${{ github.event.pull_request.user.login }}
          REVIEWER=${{ github.event.review.user.login }}
          gh pr ready $PR_NUMBER --undo
          gh pr edit --remove-label needs_initial_review
          gh pr edit --remove-label Ready_for_review
          gh pr edit --remove-label Ready_to_merge
          MESSAGE=$(sed "s/{author}/$AUTHOR/g; s/{reviewer}/$REVIEWER/g" ci_tools/bot_messages/set_draft_changes.txt)
          gh pr comment $PR_NUMBER --body "$MESSAGE"
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Update label on approval
        if: github.event.review.state == 'approved'
        uses: ./.github/actions/update_review_label
        with:
          pr_number: ${{ github.event.pull_request.number }}
