name: Mark PR as Draft on Failing Tests

on:
  check_run:
    types: [completed]

permissions:
  pull-requests: write

jobs:
  mark-draft:
    if: >
      github.event.check_run.conclusion == 'failure' &&
      github.event.check_run.pull_requests &&
      github.event.check_run.pull_requests[0]
    runs-on: ubuntu-latest

    steps:
      - name: Convert PR to draft
        run: |
          gh pr ready ${{ github.event.check_run.pull_requests[0].number }} --undo
          gh pr comment --body "Unfortunately your PR is not passing the tests so it is not quite ready for review yet."
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}

