name: Bot

on:
  pull_request_target:
    types: [ opened, reopened ]

jobs:
  Bot:
    name: Thanks for the Pull Request!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          previous_prs=$(gh pr list --author=${{ github.event.pull_request.user.login }} --json number --state=all --jq '. | length')
          if [ ${previous_prs} -eq 0 ]
          then
            gh pr comment --body-file ci_tools/bot_messages/welcome_newcomer.txt
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}

